covoiturage-gouv-fr/mono

- dashboard/src/app/modules/statistics/config/stat_main.ts
- dashboard/src/app/modules/statistics/config/stat_style.ts
Calcul effectué :  
Essence consommé en litre par mètre : 0.0000636 = 0.00005 ( kg Petrole / m ) / 1000 ( kg -> T ) / 1,048 ( TEP) / 0.750 ( T/m3 ) * 1000 ( m3 -> litre )
> Changement d'unité des statistiques pour l'essence

- api/proxy/src/HttpTransport.ts
- api/proxy/src/config/proxy.ts
- api/proxy/src/middlewares/openCorsInDev.ts
To allow access from local machines as well as from the deployed frontend, `Access-Allow-Control-Origin` is set to the Request Host dynamically.
Domains are whitelisted.
Runs in `dev` only.
> override Access-Allow-Control-Origin with request Host in dev

- dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts
- dashboard/src/app/modules/administration/pages/users/users.component.html
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
* adaptation du formulaire utilisateur
@jonathanfallon : il reste un bug : l'utilisateur admin connecté n'est pas retourné dans user:list.  
pour info : 
- affichage (vous) &  mise à jour du tableau après suppression d'un utilisateur fixé dans pr #349 
closes #170
> Gestion utilisateurs pour les admins aom & territoires

- README.md
- api/Procfile
- api/package.json
- api/scalingo/postbuild.sh
- api/services/user/src/ServiceProvider.ts
- api/services/user/src/commands/FixPermissionsCommand.ts
fix #387
Usage : `yarn permissions` inside the Api container (requires connection to MongoDB)
> add @pdc/service-user ilos fix-permissions command

- api/proxy/src/HttpTransport.ts
Un micro-fix pour avoir les codes HTTP de réponse sur `/journeys/push`
> set response status in journeys/push

- .circleci/config.yml
- dashboard/cypress.json
- dashboard/cypress/integration/territory-e2e.ts
- dashboard/cypress/support/generators/stats.generator.ts
- dashboard/package.json
- dashboard/src/app/core/entities/stat/calculatedStat.ts
- dashboard/src/app/core/interfaces/stat/calculatedStatInterface.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form/filters-form.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
* enlever les tests e2e de l'intégration continue
* génération des stats pour les 'stubs' au bon format pour cypress
* correction de l'autocomplete operators ( ajout d'un champ fieldname pour fixer les différents appels au component quand on passe des formgroups au format différents )
> Prise en compte de l'environnement sur cypress 

- dashboard/src/app/core/services/api/api.service.ts
- dashboard/src/app/modules/user/services/user.service.ts
- Définition d'un valeur par défaut pour les limite de liste (getList) dans API service
- Définition d'une limite par défaut de 10000 pour les utilisateurs
> Limite par défaut + Correctifs utilisateur

- dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list/territory-list.component.ts
Ignore la capitalisation du texte lors de recherche dans les tableaux :
- opérateur
- territoire
- utilisateurs (admin + mes utilisateurs)
> Correctif filtre de recherche

- dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
problème résolue: on ne pas sélectionné qu'un opérateur ou territoire dans les auto-completes, lié à la réinitialisation du champs à la valeur null.
> fix des autocompletes

- api/services/trip/src/providers/TripPgRepositoryProvider.ts
- dashboard/src/app/modules/stat/services/stat-format.service.ts
* prendre en compte le conducteur dans le nombre de covoitureurs
* utiliser <= et => pour le filtre par date des statistiques & trajets
> Corrections des statistiques de covoiturage - prod

- .github/CODEOWNERS
- README.md
- api/.github/PULL_REQUEST_TEMPLATE/mobility-pass.md
Ajout du fichier `.github/CODEOWNERS` pour définir les responsabilités sur les différentes parties de l'application (back et front).
Les responsables seront automatiquement assignés comme _reviewers_ sur les PR qui touchent leur code.
Plus d'infos:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
@gillesboisson, @samueleyre et @nmrgt merci de relire la répartition des dossiers pour valider que ça vous va.
Nous avions déjà détaillé par micro-service dans le backend. Vous avez la main sur le frontend.
> Code owners

- dashboard/src/environments/environment.dev.ts
Mise à jour du domaine de l'API `dev` suite à la migration du serveur sur la région OSC-FR1
> update apiUrl for new dev server in angular env

- api/scalingo/stats-refresh.js
- fix buggy sort clause on findOne
> fix query to get latest datetime from prepared collection

- dashboard/src/app/modules/stat/config/stat.ts
En attendant de finir l'implémentation, la statistique du nombre d'opérateur n'est pas affichée.
> Cacher la statistique opérateur

- api/services/user/src/actions/MeUserAction.ts
Return a 401 instead of crashing (500) when the cookie is valid in the Express session (Redis) but the user isn't found in the database. (Happens on `dev` and `staging` after flashing the database)
> return a 401 on unfound user in user:me call

- api/services/trip/src/actions/ListAction.spec.ts
- api/services/trip/src/actions/StatsAction.spec.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- api/shared/trip/common/interfaces/TripSearchInterface.ts
- api/shared/trip/common/schemas/search.ts
- dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
- dashboard/cypress/support/reusables/filter/cypress_filter.ts
- dashboard/src/app/core/entities/filter/filter.ts
- dashboard/src/app/core/interfaces/filter/filterInterface.ts
- dashboard/src/app/core/interfaces/filter/filterUxInterface.ts
- dashboard/src/app/modules/campaign/campaign.module.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/campaign-insee-filter/campaign-insee-filter-start-end-form/campaign-insee-filter-start-end-form.component.scss
- dashboard/src/app/modules/filter/components/filter/filter.component.html
- dashboard/src/app/modules/filter/components/filter/filter.component.scss
- dashboard/src/app/modules/filter/components/filter/filter.component.ts
- dashboard/src/app/modules/filter/filter.module.ts
- dashboard/src/app/modules/filter/services/filter.service.ts
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.html
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.scss
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.ts
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/services/territory-to-insees-autocomplete.service.ts
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/territory-to-insees-autocomplete.module.ts
* déplacement vers shared du component : territoryInseeAutocomplete
* Remplacement de townAutocomplete >> territoryInseeAutocomplete
BACK 
- ajouter le champs aux paramètres de l'api trip.list & trip.stat  : insees : string[] ( cf TripSearchInterface ) 
Voir #558
> Changer les filtres pour les trajets & stats : villes >> insees

- dashboard/src/app/core/const/filter.const.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
Le limit était supérieur au skip, ce qui donnait des doublons dans les trajets affichés quand on scroll. 
issue #645
> Correction du "lazy-loading" des trajets

- dashboard/src/app/core/services/store/crud-store.ts
Requête inutile.
Les crud-store appel le chargement des liste à son init, ne fonctionne pas pour les utilisateurs non connectés
> Correctif de l'appel de la l'API user:list au démarrage

- api/services/trip/src/config/cache.ts
- api/services/trip/src/providers/StatCacheRepositoryProvider.ts
#786 
Fix de l'invalidation de la cache des statistiques pour les stats globales, opérateur et territoire.
> Cache des statistiques

- api/scalingo/prebuild.sh
Pour pouvoir appliquer les mises à jour de Ilos sur sa branche `dev`, on taggue la branche `master` de l'application en 0.4.1 dans le script de déploiement. Jusque là, la version utilisée était `dev`.
> use ilos@0.4.1 on master branch

- api/services/acquisition/src/actions/LogErrorAction.ts
- api/services/acquisition/src/actions/LogRequestAction.ts
- api/services/acquisition/src/interfaces/ErrorRepositoryProviderInterface.ts
- api/services/acquisition/src/providers/ErrorPgRepositoryProvider.ts
- shared/acquisition/create.contract.ts
- shared/acquisition/logerror.contract.ts
- shared/acquisition/logrequest.contract.ts
Normalisation des interfaces d'entrée et sortie des actions. Nettoyage et fix de LogRequest.
Renommage de `create` en `log` pour enregistrer une erreur afin d'éviter la confusion avec `create` de Journey (notamment dans les interfaces).
> cleanup and fix interfaces

- dashboard/src/styles.scss
fix outline on focused elements on Chrome-like browsers
> remove outline on :focus

- api/db/migrations/20200921102502-fix-global-rule-name.js
- api/db/migrations/policy/20200921102502_fix_global_rule_name.down.sql
- api/db/migrations/policy/20200921102502_fix_global_rule_name.up.sql
Modification du nom de la règle `max_trip_per_target_restriction` en `max_trip_restriction` dans toutes les campagnes portant ce slug.
La règle a changé de nom sans que les données soient mises à jour.
> change global_rules name max_trip_restriction. fix #914

- api/providers/middleware/src/FeatureFlag/FeatureFlagMiddleware.ts
- api/providers/middleware/src/index.ts
- api/proxy/src/HttpTransport.ts
- api/services/certificate/src/ServiceProvider.ts
- api/services/certificate/src/actions/CreateCertificateAction.ts
- api/services/certificate/src/actions/DownloadCertificateAction.ts
- api/services/certificate/src/actions/FindCertificateAction.ts
- api/services/certificate/src/actions/ListCertificateAction.ts
- dashboard/src/app/core/interfaces/admin/adminLayoutInterface.ts
- dashboard/src/app/modules/administration/administration-layout/administration-layout.component.html
- dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts
- docker-compose.yml
> Feature Flag

- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.ts
- dashboard/src/app/modules/campaign/services/campaign-ui.service.ts
- nombre de trajet max dans le récap
- erreur de division par 100 pour les rétribution dans le graphique de progression de la campagne
> Correctif front : affichage campagne

- api/providers/middleware/src/HasPermissionByScope/HasPermissionByScopeMiddleware.spec.ts
- api/providers/middleware/src/HasPermissionByScope/HasPermissionByScopeMiddleware.ts
- api/providers/middleware/src/helpers.ts
- api/services/trip/src/actions/ExportAction.ts
- api/services/trip/src/actions/FinancialStatsAction.ts
- api/services/trip/src/actions/ListAction.ts
- api/services/trip/src/actions/SearchCountAction.ts
- api/services/trip/src/actions/StatsAction.ts
- api/services/trip/src/middleware/groupPermissionMiddlewaresHelper.ts
fix du bug #1326 lié à la gestion des permissions des territoires dans le middleware.
- utilisation de `authorizedTerritories` à la place de `territory_id` pour comparer l'appartenance au territoire
- ajout d'une fonction de comparaison utilisant 2 tableaux à la place de 2 entiers dans `HasPermissionByScope`.
**HOTFIX** à mettre en prod rapidement !
> Town filter

- api/.env.example
- api/proxy/src/middlewares/rateLimiter.ts
Pour palier à certaines limites lors des tests automatisés, la variable `APP_RATE_LIMITER_MAX_FACTOR` permet de multiplier le nombre max de requêtes acceptées par le _rate limiter_ du proxy.
Pour le désactiver complètement : `0`
Pour garder la configuration par défaut : `1` (valeur par défaut)
Il est possible d'utiliser un nombre à virgule (`0.1`, `1.2`...)
> Rate limiter configurable

- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.scss
#1348 
Le formulaire de création / édition de territoire est invalide si aucun enfant n'est défini pour un territoire parent.
Ajout d'un message d'erreur pour expliquer ce cas.
> Message d'erreur quand les enfants manquent

- api/proxy/src/HttpTransport.ts
- dashboard/src/app/core/const/tooltips.const.ts
- dashboard/src/app/core/interceptor/http.interceptor.ts
#1344 
Bypass du renvoi sur la page 503 pour les appels à `trip:stats` et `trip:searchcount` qui peuvent un peu trainer.
> Timeout sur les stats

- api/ilos/common/src/exceptions/TimeoutException.ts
- api/ilos/common/src/exceptions/index.ts
- api/ilos/core/src/foundation/Kernel.ts
- api/ilos/transport-http/src/helpers/mapStatusCode.ts
- api/providers/test/src/handlerMacro.ts
- api/proxy/src/config/index.ts
- api/proxy/src/config/kernel.ts
- Ajout d'un timeout configurable par `APP_REQUEST_TIMEOUT` (default : 30000)
- Ajout d'une `TimeoutException`
- Mapping du code -32408 (non-officiel) vers 408 (officiel) pour les requêtes HTTP
ticket 1358
> Ajouter un timeout sur les requêtes backend

- dashboard/src/app/shared/components/footer/footer.component.html
Cette PR ajoute la mention "Accessibilité : non conforme" à votre footer.
La mention "Accessibilité : non conforme" est obligatoire pour les sites du service public et réellement utile pour les personnes en situation de handicap.
En tant que site faisant partie du service public, nous avons un certain nombre d'obligation. 
L'une d'elle est la [**transparence du niveau d'accessibilité de votre site**](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#mention-obligatoire-sur-la-page-daccueil). 
Pour cela, il faut afficher le niveau de conformité dans le footer :
Tant que le niveau de conformité est inconnu, il est considéré comme **non conforme**.
Après avoir effectué un audit, on peut afficher : 
- Accessibilité : non conforme : score inférieur à 50 %.
- …
> Mentionne le niveau d'accessibilité dans le footer

- README.md
- docker-compose.yml
- docker/api/Dockerfile
- docker/dashboard/Dockerfile
- docker/dashboard/dev.env.js
- docker/lint/Dockerfile
- e2e.sh
- ajout d'un namespace (_project_) sur les images docker de e2e pour éviter les conflits avec les images de dev.
- utilisation des version `alpine` des images node pour limiter le tps de téléchargement :deciduous_tree:
> Namespace du docker-compose de test

- api/providers/notification/src/templates/DefaultNotification.ts
L'URL du bouton de téléchargement étant réécrite par SendInBlue (ce qui la fait planter), un quickfix pour que le lien soit utilisable en attendant mieux est de l'afficher directement dans le corps de l'email.
D'autres pistes sont exposées ici : https://github.com/betagouv/preuve-covoiturage/issues/1487
> Lien de téléchargement des exports

- api/services/trip/src/actions/ActiveCampaignExcelExportAction.spec.ts
- api/services/trip/src/actions/ActiveCampaignExcelExportAction.ts
La cron qui se charge de déclencher la création des appels de fonds n'a pas run pour le mois d'Octobre.
Conditionner le run à l'environnement de prod n'est pas une bonne chose selon moi.
> fix: remove production env check for apdf cron process

- api/services/acquisition/tsconfig.json
- api/services/application/tsconfig.json
- api/services/carpool/tsconfig.json
- api/services/certificate/tsconfig.json
- api/services/company/tsconfig.json
- api/services/fraud/tsconfig.json
- api/services/honor/tsconfig.json
- api/services/monitoring/tsconfig.json
- api/services/normalization/tsconfig.json
- api/services/operator/tsconfig.json
- api/services/policy/tsconfig.json
- api/services/territory/tsconfig.json
- api/services/trip/tsconfig.json
Lien symbolique sur le tsconfig de api pour tous les sous modules:
- Exclusion des tests pour la phase de build (la partie perf ... même si c'est pas énorme)
- Même tsconfig pour tout les sous modules d'api
> conf: use sym link to use single tsconf

- api/ilos/connection-redis/src/RedisConnection.ts
- api/ilos/transport-redis/src/QueueTransport.ts
Une nouvelle connexion est créée par queue comme indiqué ici : https://github.com/OptimalBits/bull/issues/1192
> fix Redis warnings

- api/services/trip/src/actions/BuildExportAction.ts
fileKey doit être retourné pour l'action SendExport
> fix: return s3 filKey instead of path

- api/services/trip/src/actions/BuildExportAction.ts
Suppressions des colonnes suivantes pour l'opendata : 
- journey_start_towngroup (inutile)
- journey_end_towngroup (inutile)
- passenger_card (très souvent vide)
- passenger_over_18 (donnée identifiante)
- driver_card (très souvent vide)
Ça permet de réduire pas mal la taille des exports sur un gros volume de données
> fix: fixed fields for opendata, remove unused

- api/services/policy/src/providers/IncentiveRepositoryProvider.ts
Avant, les trajets non 'ok' n'étaient pas du tout calculé. Maintenant ils arrivent dans le moteur de calcul. Il faut donc : 
- flagger les trajets qui sont non seulement canceled mais aussi en fraudcheck_error (avec le state = disabled)
- exclure ces incitations des export en passant le statut de l'incitation à error
> fix: avoid using incentive result if carpool status not ok

- README.md
- api/db/migrations/20211214213748-update-trip-listview.js
- api/db/migrations/trip/20211214213748_update_trip_listview.down.sql
- api/db/migrations/trip/20211214213748_update_trip_listview.up.sql
#1608
Ajout d'une migration pour remplacer `trip.list_view` sans filtrer par statut de `carpool`. Celà permet à l'action `carpool:updateStatus` de fonctionner correctement et de répliquer les modifs (faites par la fraude, par exemple) dans `trip.list`.
TODO : mettre à jour les 37k+ trajets dont le statut n'est pas `ok` dans `trip.list`.
> Trigger update de trajets

- api/Procfile
Suppression de `LOG_LEVEL=info` dans le `Procfile` pour éviter d'écraser la config passée dans les variables d'environnement.
```
scalingo -a pdc-prod env-set LOG_LEVEL=info
scalingo -a pdc-prod restart
```
> remove LOG_LEVEL setting on worker

- api/services/territory/src/providers/GeoRepositoryProvider.ts
- shared/territory/common/geo/GeoCodeTypeEnum.ts
Actuellement il  y a plusieurs lignes de retour pour la recherche d'une ville (code postale et code insee).
Afin de fix ça, je fais une jointure avec `territory.territory_codes`
Cela peu poser problème lors du paramétrage d'une campagne avec des exclusions
> fix: remove duplicate city response that could lead to wrong insee

- api/proxy/src/HttpTransport.ts
Y'a un autre timeout à 45 secondes mais ça sera toujours 15 secondes de plus actuellement
> fix(proxy): update timeout for stats endpoint only

- api/services/trip/src/actions/excel/build/BuildFilepath.ts
Les APDFs ont été générés avec des noms de mois à "février" (à cause du timezone) alors que les trajets sont biens de mars
> fix(BuildFilePath): fix bad month string because of start_date timezone

- api/package.json
- api/services/trip/src/actions/opendata/BuildResourceDescription.ts
- api/yarn.lock
Même erreur que pour les APDF [ici](https://github.com/betagouv/preuve-covoiturage/pull/1714) ...
Provoque un décalage de -1 mois sur la description des datasets
> fix(BuildResourceDescription): add 6 days to fix issue with timezone

- api/cron.json
- api/proxy/src/Kernel.ts
- api/proxy/src/commands/StatsRefreshCommand.ts
Lancé tous les lundis à 3h du matin.
- liste les vues matérialisées du schéma `stats` et rafraîchi les données
- utilise la fonctionnalité de Scalingo `cron.json` pour lancer la commande de refresh
> Ajout d'un cron pour le refresh des vues de stats

- api/ilos/core/src/foundation/Kernel.ts
- api/proxy/src/Kernel.ts
- api/proxy/src/commands/ProcessAcquisitionCommand.ts
- api/services/carpool/src/providers/CrosscheckRepositoryProvider.ts
- api/services/normalization/src/actions/NormalizationProcessAction.ts
Passage de +/- 2h à +/- 10 minutes pour le recollement de trajets.
- ajout de la commande `process:acquisition`
- nettoyage de quelques console.debug trop verbeux
> Algo de consolidation des `trip_id`

- api/providers/validator/package.json
- api/providers/validator/src/formats/phoneCustomFormat.spec.ts
- api/yarn.lock
Mise à jour de `libphonenumber` pour régler un problème de validation des numéros Réunionais (+262).
Test mis à jour avec le numéro problématique (tronqué)
TODO : **merger en hotfix sur la branche déployée**
> Bump de libphonenumber

- api/services/trip/src/providers/TripRepositoryProvider.ts
L'argument par défaut coalesce 0 n'étant présent pour la somme du 2ème éléments du tableau d'incentive produisait un null + 0 => un Nan dans les APDF
> fix(TripRepositoryProvider): add missing colaesc for slices

- api/proxy/src/commands/StatsRefreshCommand.ts
Le CRON `stats:refresh` lancé chaque semaine utilise le timeout Postgresql par défaut et ne termine pas son execution.
J'ai écrasé `APP_POSTGRES_TIMEOUT` directement en amont de la création de la connexion Postgresql :
1. pour simplifier l'implémentation et coller aux pratiques utilisées ailleurs
2. parce que c'est une commande exécutée dans son propre environnement et que ça ne va pas polluer les autres containers.
> Fix du timeout de `stats:refresh`

- api/services/certificate/src/providers/CarpoolPgRepositoryProvider.ts
@jonathanfallon concernant [le ticket de support](https://covoiturage-betagouv.zammad.com/#ticket/zoom/36). 
- Est-ce que tu vois des impactes à prendre les trajets en 'expired' pour les attestations ?
- Est-ce qu'il y a d'autres devs à faire ?
> fix(CCPgRepositoryProvider): add carpool status expired

- api/services/trip/src/actions/ExportCapitalCallsAction.ts
- api/services/trip/src/actions/excel/BuildExcel.ts
- api/services/trip/src/actions/excel/CheckCampaign.spec.ts
- api/services/trip/src/actions/excel/CheckCampaign.ts
- api/services/trip/src/interfaces/TripRepositoryProviderInterface.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- use the same selector as getPolicyStats in getPolicyCursor
Il reste un soucis sur la somme des incitations qui n'est pas égale à celle des stats. C'est probablement dû au fait que ça utilise `driver_incentives_rpc_sum` alors que les stats font la somme des `policy.incentives.amount`.
> Fix de la liste de trajets dans le fichier APDF

- api/services/policy/src/engine/policies/Pdll.html.ts
L'exclusion est bien dans le code depuis le début.
> Ajout de Chôlet dans la description de la campagne PDLL

- api/.buildpacks
- api/Aptfile
- api/yarn.lock
- docker/api/Dockerfile
Ajout de cmake g++ python3 dans l'image Docker et dépendances Scalingo pour que le build de `node-gyp` fonctionne.
> FIX node-gyp build

- api/services/certificate/src/providers/CarpoolPgRepositoryProvider.ts
Utilisation de `UNION ALL` pour ne pas supprimer les résultats avec des données identiques (typiquement sur l'heure de départ).
> [hotfix] nb de trajets dans les attestations

- docker/postgres/Dockerfile
bump PostgreSQL to 14 and PostGIS to 3.3
Après un rebuild complet des images, le container Postgres ne va pas booter avec la version de la db du dossier `db/postgres`.
Le plus simple est de faire un `rm -rf db/postgres/*` et de refaire un `pg_restore` complet.
Instructions ici : https://hackmd.io/zRF5bXnjSdSuoygxN-a8BQ
> MAJ de PostgreSQL

- api/services/acquisition/src/actions/CreateJourneyAction.ts
On relance l'erreur à la fin du catch sans la modifier pour garder le contexte et la cause.
> Retour d'erreur sur l'acquisition

- api/providers/geo/src/providers/LocalGeoProvider.ts
- api/proxy/load/acquisition_create.js
Suite à l'évolution en 1.2.1 du paquet geo, il est possible d'utiliser `geo.get_closest_country` à la place de `geo.get_latest_by_point` pour résoudre le code INSEE d'un point géographique.
Les contours des pays limitrophes étant volontairement imprécis pour des raisons de performances, il est nécessaire d'utiliser cette fonction de résolution.
**POST DEPLOY**
```sql
-- copie des preuves concernées
create table tmp_replay_errors as (select * from acquisition.acquisitions where error_stage = 'normalization');
-- reset du statut des preuves
update acquisition.acquisitions set status = 'pending' where _id in (select _id from tmp_replay_errors);
-- update des trajets passés en carpool quand c'est terminé
-- TODO
-- cleanup
DROP TABLE tmp_replay_errors;
```
> [fix] résolution des INSEE des pays voisins

- api/ilos/framework/package.json
- api/services/policy/src/actions/FundingRequestsListAction.ts
- api/services/policy/src/config/apdf.ts
- api/services/policy/src/config/index.ts
- api/services/policy/src/interfaces/providers/FundingRequestsRepositoryProviderInterface.ts
- api/services/policy/src/providers/FundingRequestsRepositoryProvider.ts
- shared/user/permissions.config.ts
#1951 
Possibilité de masquer les APDF du mois dernier aux opérateurs et territoires en attendant la validation du RPC.
Passer la variable d'environnement `APP_APDF_SHOW_LAST_MONTH` à `false` pour les masquer.
> Affichage conditionnel des APDF

- shared/certificate/common/interfaces/IdentityIdentifiersInterface.ts
#1945 
Ajout de la possibilité de créer un attestation uniquement avec l'`operator_user_id`.
> Attestation sans `phone_trunc`

- api/doc/v2.yaml
Correction d'une faute dans la doc (https://tech.covoiturage.beta.gouv.fr/operateurs/api-v2.html)
```diff
- icentives
+ incentives
```
> fix(doc): correct typo

- api/services/certificate/src/actions/CreateCertificateAction.spec.ts
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-list.component.html
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-list.component.ts
- dashboard/src/app/modules/certificate/services/certificate-api.service.ts
- shared/certificate/common/interfaces/IdentityIdentifiersInterface.ts
- shared/certificate/download.contract.ts
> [frontend] création des attestations opérateur avec `operator_user_id` uniquement

- api/services/policy/src/actions/SimulateOnPastAction.ts
- api/services/policy/src/actions/SimulateOnPastByGeoAction.ts
Fix la simulation draft de Normandie. 
Si un trajet était en erreur à cause du référentiel geo, ça faisait crash la simulation entière et on est pas au trajet prêt.
> fix(policy): try catch on each trip to avoid computation abort

- api/services/fraud/src/actions/CheckPendingAction.ts
- api/services/fraud/src/providers/FraudCheckRepositoryProvider.integration.spec.ts
- api/services/fraud/src/providers/FraudCheckRepositoryProvider.ts
Fix de l'erreur
```json
{
"level": 50,
"time": 1675859163850,
"pid": 63,
"hostname": "pdc-prod-worker-1",
"err": {
"type": "Error",
"message": "Release called on client which has already been released to the pool.",
"stack": "Error: Release called on client which has already been released to the pool.
at throwOnDoubleRelease (/app/node_modules/pg-pool/index.js:27:9)
at Client.release (/app/node_modules/pg-pool/index.js:318:9)
at /app/services/fraud/dist/providers/FraudCheckRepositoryProvider.js:96:34
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)"
},
"msg": "unhandled promise rejection"
}
```
> fix: avoid double free

- api/db/package.json
- api/yarn.lock
Bump de la lib evolution-geo et nettoyage des dépendances.
La v1.2.4 ne migre pas les centroids à chaque déploiement !
> bump @betagouvpdc/evolution-geo to 1.2.4

- api/services/policy/src/providers/IncentiveRepositoryProvider.ts
Utilisation de `amount` à la place de `result` pour le calcul de `incentive_sum` dans la table policies.
`amount` est le montant corrigé par l'action `campaign:finalize` après application des règles stateful.
`result` est le montant calculé par `campaign:apply`
> Fix du calcul de incentive_sum

- api/ilos/cli/src/commands/CallCommand.ts
Amélioration du parsing JSON de ilos call pour ne pas crasher quand on passe une chaine vide ou que le param `-p` ou `-c` n'est pas passé.
les erreurs sont remontées par l'action appelée si les params ou le contexte ne sont pas bons.
> Amélioration du parsing JSON de ilos call

- api/services/apdf/src/providers/StorageRepositoryProvider.ts
- shared/apdf/list.contract.ts
- shared/apdf/list.schema.ts
Ajout de `territory_id` dans le schema de `apdf:list` car le middleware l'injecte quand l'utilisateur est un territoire.
> [hotfix] listing des APDF pour les territoires

- .github/workflows/deploy-doc-production.yml
Force nodeJS 16.
Working build => https://github.com/betagouv/preuve-covoiturage/actions/runs/4512630793/jobs/7946350939?pr=2084
> fix(github): force node 16 install to avoid node 17 build error

- api/package.json
Fix du script `npm run ilos` pour pouvoir passer des arguments
ex
`npm run ilos campaign:apply --help`
--> `npm run -w @pdc/proxy -- ilos campaign:apply --help`
> npm run ilos

- dashboard/src/app/modules/campaign/pages/campaign-apdf/campaign-apdf.component.html
#1761
L'historique complet des APDF est affiché et non les 6 derniers mois.
Mise à jour du titre pour refléter le changement.
TODO : Fermer la #1761 quand la PR est fusionnée
> Suppression des mois dans le titre des APDF

- api/services/cee/src/actions/RegisterCeeAction.ts
Chaining ternaries like this makes the code difficult to parse.
While TS doesn't support an instance-of switch statement, there exists a solid workaround, such as proposed here.
> Make code more readable by avoiding chaining ternary ops

- api/services/apdf/src/helpers/getDeclaredOperators.spec.ts
- api/services/operator/src/providers/OperatorPgRepositoryProvider.ts
Fix du retour de la fonction `findBySiret`.
Attention, certains opérateurs ont le même SIRET.
#2187
> Listing operators by SIRET

- api/services/policy/src/actions/ApplyAction.ts
- api/services/policy/src/commands/ApplyCommand.ts
Fix de la gestion des dates dans `campaign:apply` action.
Quand la campagne est terminée mais encore active, on vérifie que le `from` est avant la date de fin de la campagne.
Ajout d'un try/catch pour pouvoir continuer à traiter les campagnes de la liste même si l'une d'elles crash.
> [fix] campaign:apply

- api/proxy/src/HttpTransport.ts
Fix de la Regex de observatory / geo/search suite à la remontée d'erreur du scan de code Github.
> fix(proxy): case sensitive regex code scanning error

- api/services/acquisition/src/actions/ProcessJourneyAction.ts
Le temps de démarrage du conteneur prend autant voire plus de temps que le process de batch en lui même.
> fix(cron): udpate acq processing batch size

- api/services/policy/src/engine/policies/Idfm.ts
- api/services/policy/src/interfaces/engine/PolicyInterface.ts
- shared/policy/common/interfaces/PolicyInterface.ts
- renommage de `pollutionAndStrikeDates` en `boosterDates` dans le fichier de configuration des campagnes
- ajout de `booster_dates` dans les paramètres pour permettre une utilisation dans les exports
> feat: add booster date policy param

- public/package-lock.json
- public/src/app/observatoire/territoire/Dashboard.tsx
- public/src/app/observatoire/territoire/KeyFigures.tsx
- public/src/app/observatoire/territoire/graphs/DistanceGraph.tsx
- public/src/app/observatoire/territoire/graphs/FluxGraph.tsx
- public/src/app/observatoire/territoire/graphs/IncentiveGraph.tsx
- public/src/app/observatoire/territoire/graphs/OccupationGraph.tsx
- public/src/app/observatoire/territoire/graphs/RepartitionDistanceGraph.tsx
- public/src/app/observatoire/territoire/graphs/RepartitionHoraireGraph.tsx
- public/src/app/observatoire/territoire/maps/AiresMap.tsx
- public/src/app/observatoire/territoire/maps/DensiteMap.tsx
- public/src/app/observatoire/territoire/maps/FluxMap.tsx
- public/src/app/observatoire/territoire/maps/OccupationMap.tsx
- public/src/app/observatoire/territoire/tables/BestFluxTable.tsx
- public/src/app/observatoire/territoire/tables/BestTerritoriesTable.tsx
- public/src/components/observatoire/SelectIncentiveTerritory.tsx
- public/src/components/observatoire/SelectMonth.tsx
- public/src/components/observatoire/SelectObserve.tsx
- public/src/components/observatoire/SelectPeriod.tsx
- public/src/components/observatoire/SelectSemester.tsx
- public/src/components/observatoire/SelectTerritory.tsx
- public/src/components/observatoire/SelectTrimester.tsx
- public/src/components/observatoire/SelectYear.tsx
- public/src/context/DashboardProvider.tsx
- public/src/helpers/api.ts
- public/src/helpers/dashboard.ts
```
│       │
│
```
- feat: A new feature (Minor bump)
- fix: A bug fix (Patch bump)
- perf: A code …
> fix(obs): build

- .github/pull_request_template.md
- api/specs/api-v3.1.yaml
- api/src/pdc/services/cee/helpers/getOperatorIdOrFail.ts
```
│       │
│
```
- feat: A new feature (Minor bump)
- fix: A bug fix (Patch bump)
- perf: A code …
> MAJ documentation technique

- api/src/pdc/services/policy/engine/policies/20230401_PaysBasqueAdour.html.ts
- api/src/pdc/services/policy/engine/policies/20230401_PaysBasqueAdour.ts
https://covoiturage-betagouv.zammad.com/#ticket/zoom/4848
Mise à jour de la campagne :
- enveloppe de 325 000,00 €
- Suppression de Karos au 01/01/2025
- Changement du plafond mensuel à 100,00 €
```sql
UPDATE policy.policies
SET name = 'Pays Basque Adour 2025',
max_amount = 32500000,
end_date = '2025-01-01T00:00:00+0200',
status = 'active'
WHERE _id = 946
```
> Update de campagne : PBA 2023-2025

- api/src/pdc/providers/datagouv/DataGouvAPIProvider.ts
- api/src/pdc/providers/datagouv/DataGouvAPITypes.ts
- api/src/pdc/providers/datagouv/DataGouvMetadataProvider.ts
- api/src/pdc/services/export/ExportServiceProvider.ts
- api/src/pdc/services/export/commands/DataGouvCommand.ts
- api/src/pdc/services/export/config/datagouv.ts
- api/src/pdc/services/export/repositories/CarpoolRepository.ts
- api/src/pdc/services/export/repositories/queries/AbstractQuery.ts
- api/src/pdc/services/export/repositories/queries/DataGouvListQuery.ts
- api/src/pdc/services/export/repositories/queries/DataGouvStatsQuery.ts
- api/src/pdc/services/export/services/DataGouvFileCreatorService.ts
Ajout de l'upload via l'API data.gouv.fr à la commande `export:datagouv`.
:warning: ajouter les variables d'environnement à l'infra lors du déploiement
```
APP_DATAGOUV_ENABLED=true
APP_DATAGOUV_KEY=...
APP_DATAGOUV_URL=https://www.data.gouv.fr/api/1/
APP_DATAGOUV_DATASET=5e8ee97c16601da4ee24ffb7
```
<details>
```
│       │
│
└─⫸ Commit Type: …
```
> Upload data.gouv.fr
