covoiturage-gouv-fr/mono

- api/src/routes/stats/service.js
J'ai supprimé les 36 entrées avec des dates au mauvais format.
> fix: date of passenger/start/datetime for stats

- dashboard/src/app/config/main.ts
- dashboard/src/app/entities/database/operator.ts
- dashboard/src/app/modules/aom/modules/dialog/components/form/component.ts
- dashboard/src/app/modules/aom/modules/dialog/components/form/template.html
- dashboard/src/app/modules/aom/modules/ui/components/view/template.html
- dashboard/src/app/modules/aom/pages/statistics/component.ts
- dashboard/src/app/modules/aom/pages/statistics/style.scss
- dashboard/src/app/modules/aom/pages/statistics/template.html
- dashboard/src/app/modules/journeys/components/filter/template.html
- dashboard/src/app/modules/journeys/components/list/component.ts
- dashboard/src/app/modules/journeys/components/list/template.html
- dashboard/src/app/modules/operator/modules/operators/dialog/components/form/component.ts
- dashboard/src/app/modules/operator/modules/operators/dialog/components/form/template.html
- dashboard/src/app/modules/operator/modules/operators/dialog/dialog.module.ts
- dashboard/src/app/modules/statistics/config/stat_main.ts
- dashboard/src/app/modules/statistics/config/stat_style.ts
- dashboard/src/app/modules/statistics/modules/ui/components/graphs/template.html
- dashboard/src/app/modules/statistics/modules/ui/components/number/style.scss
- dashboard/src/app/modules/statistics/modules/ui/components/resume/template.html
- dashboard/src/app/modules/statistics/pages/statistics/component.ts
- dashboard/src/app/modules/statistics/pages/statistics/template.html
- dashboard/src/app/modules/user/modules/ui/components/dropdown/component.ts
- dashboard/src/app/shared/modules/form/components/contacts/component.ts
- dashboard/src/app/shared/modules/form/components/contacts/form.ts
- dashboard/src/app/shared/modules/form/components/contacts/template.html
- dashboard/src/app/shared/modules/form/form.module.ts
close: #24 #13 #30 #26 #20 #11
> Corrections des stats, filtres, contacts sur le front

- api/services/incentive/package.json
- api/services/incentive/transports/http.js
- api/shared/middlewares/accept-csv.js
#131 
Remarque : Pas encore testé.
> Ajout des filtres par AOM et Opérateurs pour la route incentive

- dashboard/src/app/app-routing.module.ts
@jonathanfallon Ce n'est pas possible de faire une 301 côté front, ce doit être côté serveur.
> Redirection de statistics vers stats

- api/services/organization/operator.js
- dashboard/src/app/modules/aom/modules/dialog/components/form/component.ts
- dashboard/src/app/modules/aom/modules/dialog/components/form/template.html
- dashboard/src/app/modules/aom/modules/ui/components/view/template.html
- dashboard/src/app/modules/operator/modules/operators/dialog/components/form/component.ts
- dashboard/src/app/modules/operator/modules/operators/dialog/components/form/template.html
- dashboard/src/app/modules/user/modules/ui/components/dropdown/component.ts
- dashboard/src/app/modules/user/modules/ui/components/dropdown/template.html
- dashboard/src/app/shared/modules/form/components/address/component.ts
- dashboard/src/app/shared/modules/form/components/company/component.ts
- dashboard/src/app/shared/modules/form/components/contacts/template.html
> Correction de l'édition des champs contacts AOMs et Opérateurs

- README.md
- api/proxy/app.js
- api/services/policy/entities/schemas/policy.js
- api/services/policy/kernel/filters/hasInsee.js
- api/services/policy/kernel/filters/hasInsee.spec.js
- dashboard/src/app/modules/incentive/components/filters/form/component.ts
- dashboard/src/app/modules/incentive/components/filters/insee/component.ts
- dashboard/src/app/modules/incentive/components/filters/insee/template.html
- dashboard/src/app/modules/incentive/filters/InseeFilter.ts
- dashboard/src/app/modules/incentive/filters/RankFilter.ts
- dashboard/src/app/modules/incentive/filters/WeekDayFilter.ts
- dashboard/src/app/modules/incentive/pages/policies/create/component.ts
- dashboard/src/app/modules/incentive/pages/policies/create/template.html
* mise à jour du schema policy
* mise à jour des testes et de l'application des règles d'incitations
* mise à jour du filtre en front
> Ajout des possibilités de filtrer par ET et OU pour les filtres par insees des politiques 

- README.md
Testing the contribution process with an external Github account
> Add contribution process

- dashboard/src/app/modules/statistics/modules/ui/stats/component.ts
- dashboard/src/app/modules/statistics/modules/ui/stats/style.scss
- dashboard/src/app/modules/statistics/modules/ui/stats/template.html
- docker/dashboard/Dockerfile
Ajout du message suivant sur la page statistiques : "Ces données sont collectées à partir des informations communiquées par les opérateurs partenaires. Il ne s'agit en aucun cas d'une représentation exhaustive du covoiturage en France."
fixes #212
> Ajout d'un message de précision sur la page statistique

- api/services/trip/service.js
- track trip resolution times by op_journey_id and driver identity
> track trip resolution times

- dashboard/src/app/modules/statistics/modules/ui/stats/component.ts
- dashboard/src/app/modules/statistics/modules/ui/stats/style.scss
- dashboard/src/app/modules/statistics/modules/ui/stats/template.html
- docker/dashboard/Dockerfile
* Ajout d'une bannière sur la page statistiques
cf pr #211
> Bannière de la page statistiques ( cherry-pick de master )

- dashboard/src/app/app-routing.module.ts
- dashboard/src/app/shared/layout/components/menu/component.ts
> hotfix: remove incentive module

- api/services/user/entities/models/user.js
> retirer l'envoie d'email d'invitation sur la production

- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-autocomplete/territory-autocomplete.component.ts
- dashboard/src/app/modules/territory/services/territory.service.ts
Auto complete support for user crud
> User create : territory auto complete based on api.services : list

- api/services/user/src/entities/User.ts
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.html
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
- dashboard/src/app/shared/directives/button-spinner.directive.ts
- Fix visual bugs
- Remove fake data
- Clean old TODOS
> User Front/rpc clean

- dashboard/src/app/core/enums/campaign/campaign-status.enum.ts
- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-4/summary-form/summary-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/step-4/summary-form/summary-form.component.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.scss
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.ts
- dashboard/src/app/modules/campaign/services/campaign.service.ts
* connexion du lancement de la campagne avec l'API
* mise à jour dashboard campagne
> Lancement de la campagne dans dashboard

- api/services/trip/src/actions/ListAction.ts
- api/services/trip/src/actions/StatsAction.ts
- api/services/user/src/config/permissions.ts
- dashboard/src/app/modules/stat/services/stat.service.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
- dashboard/src/app/modules/trip/pages/trip-stats/trip-stats.component.html
- dashboard/src/app/modules/trip/services/trip.service.ts
* Front
* connexion à l'api
* Back
* ajout des permissions et des middlewares
lié à l'issue : #355
> Corriger la vue des stats et des trajets côté opérateurs

- api/services/fraud/.gitignore
- api/services/fraud/package.json
- api/services/fraud/src/ServiceProvider.spec.ts
- api/services/fraud/src/ServiceProvider.ts
- api/services/fraud/src/actions/FraudExampleAction.ts
- api/services/fraud/src/bootstrap.ts
- api/services/fraud/src/config/connections.ts
- api/services/fraud/src/interfaces/FraudCheck.ts
- api/services/fraud/src/interfaces/FraudCheckRepositoryProviderInterface.ts
- api/services/fraud/src/interfaces/index.ts
- api/services/fraud/src/migrations/001_create_fraud_tables.sql
- api/services/fraud/src/providers/FraudCheckRepositoryProvider.ts
- api/services/fraud/tests/FraudService.spec.ts
- api/services/fraud/tsconfig.json
> feat(fraud): add fraud check service (canvas)

- api/services/trip/src/actions/ListAction.ts
- api/services/trip/src/providers/TripPgRepositoryProvider.ts
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
- Mise à jours du schema (trip > Journey)
- Adaptation de la liste 
Fix #368
> Formatage tableau des trajets

- .circleci/config.yml
- dashboard/src/environments/environment.dev.ts
> Cypress CI

- api/providers/schema/src/models/contacts/schemas/contactSchema.ts
- api/providers/schema/src/models/contacts/schemas/contactsSchema.ts
- api/providers/schema/src/models/operator/schemas/operatorCreateSchema.ts
- api/providers/schema/src/models/operator/schemas/operatorPatchContactsSchema.ts
- api/providers/schema/src/models/territory/schemas/territoryCreateSchema.ts
- api/providers/schema/src/models/territory/schemas/territoryPatchContactsSchema.ts
- api/proxy/src/HttpTransport.ts
- api/services/user/src/actions/CreateUserAction.ts
- api/services/user/src/actions/ForgottenPasswordUserAction.ts
- api/services/user/src/actions/PatchUserAction.ts
- api/services/user/src/actions/SendConfirmEmailUserAction.ts
Always set the status based on the RPC response error code.
- POST journeys
- Auth endpoints
- RPC endpoint
> fix proxy http status

- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/modules/administration/pages/territory/territory.component.ts
- dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-autocomplete/territory-autocomplete.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-details/territory-details.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.ts
- Revue de la gestion des évènement de selection / click / focus des composant dropdown
+ Correctif d'un double affichage des fiches de contacts dans profile.operator / profile.territory
> Correctif : dropdown operateur territoire (ordi margot)

- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-autocomplete/territory-autocomplete.component.ts
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
fix #407 : Bug lien id operateur
fix #448 : Impossibilité d'éditer des utilisateurs sans prénom
> Correctif creation / edition utilisateur

- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
- dashboard/src/app/modules/user/services/user.service.ts
Correction des erreur de conflit d'email, changement du format des message coté backend
> Correctif email en double

- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.html
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
- dashboard/src/app/modules/administration/pages/users/users.component.html
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- application du test de permission user.update sur les composant de listing des users
- intégration du form d'edition utilisateur dans  le composant users (territoire, operateur)
> Possibilité d'éditer les utilisateurs pour les Opérateurs et Territoires

- dashboard/cypress/integration/integration.ts
- dashboard/cypress/support/reusables/auth/cypress_login.ts
- dashboard/cypress/support/stories/operator.story.ts
- dashboard/cypress/support/stories/registry.story.ts
- dashboard/cypress/support/stories/territory.story.ts
- dashboard/cypress/support/stubs/user/user.me.ts
- dashboard/src/app/core/guards/login-guard.service.ts
- dashboard/src/app/modules/authentication/authentication-routing.module.ts
Redirection de login :
redirection vers les campagne pur les utilisateurs territoires
redirection vers la page de stats pour les autres
> Redirection vers la page d'accueil pour les utilisateurs connecté depuis la page login

- .circleci/config.yml
- dashboard/cypress/integration/integration.ts
- dashboard/cypress/support/apiValues/expectedFilter.ts
- dashboard/cypress/support/reusables/filter/cypress_filter.ts
- dashboard/cypress/support/stubs/territory/territory.find.ts
- dashboard/src/app/core/entities/shared/contacts.ts
- dashboard/src/app/modules/filter/components/filter/filter.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
- dashboard/src/app/modules/stat/config/statNumbers.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
> Ajouter le filtrage sur l'autocomplete des territoires

- api/providers/schema/src/models/user/schemas/index.ts
- api/providers/schema/src/models/user/schemas/userSendInvitationEmailSchema.ts
- api/services/user/src/ServiceProvider.ts
- api/services/user/src/actions/SendInvitationEmailUserAction.ts
- api/services/user/src/actions/index.ts
- dashboard/src/app/core/services/authentication/authentication.service.ts
- Création d'une action dans le backend pour le ré-envoi de l'invitation
- Lien du front vers les ré-envoi
fix #146
> Front : ré-envoi de l'invitation

- api/services/trip/src/providers/TripPgRepositoryProvider.ts
- dashboard/src/app/modules/filter/services/filter.service.ts
**FRONT**
Traduire la distance en mètre
**BACK**
Mettre la comparaison des valeurs dans le bon sens
> Corriger le filtrage par distance

- dashboard/cypress/integration/e2e.ts
- dashboard/cypress/integration/integration.ts
- dashboard/cypress/support/apiValues/expectedTemplates.ts
- dashboard/cypress/support/apiValues/expectedTerritory.ts
- dashboard/cypress/support/reusables/auth/cypress_login.ts
- dashboard/cypress/support/reusables/auth/cypress_logout.ts
- dashboard/cypress/support/reusables/campaign/cypress_campaign_create.ts
- dashboard/cypress/support/reusables/campaign/cypress_campaign_create_from_template.ts
- dashboard/cypress/support/reusables/campaign/cypress_campaign_edit.ts
- dashboard/cypress/support/reusables/campaign/cypress_campaign_edit_created_from_template.ts
- dashboard/cypress/support/reusables/campaign/cypress_campaign_launch.ts
- dashboard/cypress/support/reusables/campaign/steps/campaign-create-first-step.ts
- dashboard/cypress/support/reusables/campaign/steps/campaign-create-fourth-step.ts
- dashboard/cypress/support/reusables/filter/cypress_filter.ts
- dashboard/cypress/support/reusables/notification.cypress.ts
- dashboard/cypress/support/reusables/operator/application.cypress.ts
- dashboard/cypress/support/reusables/operator/cypress_operator.ts
- dashboard/cypress/support/reusables/profile/cypress_profile.ts
- dashboard/cypress/support/reusables/territory/cypress_territory.ts
- dashboard/cypress/support/stories/operator.e2e.story.ts
- dashboard/cypress/support/stories/registry.e2e.story.ts
- dashboard/cypress/support/stories/territory.e2e.story.ts
- dashboard/cypress/support/stories/territory.story.ts
- dashboard/cypress/support/stubs/campaign/campaign-template.list.ts
- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
intégration :  test de la création de campagnes à partir des templates mockés 
e2e: test de la création et l'édition de campagnes créés à partir des templates mockés
> Ajout des tests pour les templates

- dashboard/src/app/core/operators/catchHttpStatus.ts
- dashboard/src/app/core/services/api/json-rpc.service.ts
- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/modules/authentication/pages/forgotten-password/forgotten-password.component.ts
- création d 'un opérateur permettant le catch des erreur http
- remplacement des check d'erreur par cet opérateur
- implémentation du catch de l'erreur 404 pour les emails non valide lors du process d'oubli de mot de passe close #487
> Gestion des erreur HTTP + retour erreur email non valide

- api/services/trip/src/providers/TripPgRepositoryProvider.ts
> hotfix(trip): trip subsidized stats

- api/db/migrations/territory/001_create_territory_table.up.sql
- api/proxy/package.json
- api/proxy/src/Kernel.ts
- api/proxy/src/commands/InseeSeedCommand.ts
- api/proxy/src/commands/MapIdCommand.ts
- api/services/acquisition/src/actions/LogAction.ts
- api/services/acquisition/src/commands/MigrateDataCommand.ts
- api/services/application/src/commands/MigrateDataCommand.ts
- api/services/operator/src/commands/MigrateDataCommand.ts
- api/services/territory/package.json
- api/services/territory/src/ServiceProvider.ts
- api/services/territory/src/commands/MigrateDataCommand.ts
- api/services/trip/src/commands/MigrateDataCommand.ts
\* see HackMD doc about migration for errors (internal)
\** Guessing the most probable institution based on NAF code. Defaults to main institution SIRET.
> mapid command

- dashboard/cypress/support/reusables/campaign/steps/campaign-create-second-step.ts
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form/filters-form.component.html
- dashboard/src/app/modules/filter/components/towns-autocomplete/towns-autocomplete.component.ts
- dashboard/src/app/modules/filter/services/town.service.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
* corrections de la réinitialisation des filtres par communes 
* réaffichage de l'utilisateur connecté en retirant les actions lié à cette utilisateur dans le tableau 
Corrige #529 #532 #547 #545 #544 #546 #547 #548
> Grammaire, filtre communes et affichage utilisateur connecté dans tableau  

- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/actions/PublicStatsAction.ts
- api/shared/trip/publicStats.contract.ts
- api/shared/trip/publicStats.schema.ts
- dashboard/src/app/app-routing.module.ts
- dashboard/src/app/core/const/main.const.ts
- dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.html
- dashboard/src/app/modules/stat/config/stat.ts
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.scss
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.ts
- dashboard/src/app/modules/stat/services/stat-public.service.ts
- dashboard/src/app/modules/stat/stat-routing.module.ts
- dashboard/src/app/modules/stat/stat.module.ts
- dashboard/src/app/shared/components/header/header.component.html
- dashboard/src/app/shared/components/header/header.component.ts
**FRONT**
Création de la page statistiques : '/stats'
* Message en attendant d'avoir les données à jour : 'Les statistiques ne sont pas disponibles actuellement.'
* Mise à jour du lien du logo quand on est sur la page statistiques pour retourner vers le CMS 
* Connexion à l'API
**BACK**
* Action trip:publicStats pour récupérer les statistiques globales. 
TODO: pas encore testé en local
> WIP - Page publique statistiques 

- dashboard/src/app/modules/stat/services/stat-format.service.ts
prendre en compte le conducteur dans le nombre de covoitureurs
> Corrections stats - carpooling

- api/proxy/src/commands/MapIdCommand.ts
- api/services/company/src/actions/FetchAction.ts
- api/services/company/src/actions/FindAction.ts
- api/services/company/src/providers/CompanyDataSourceProvider.ts
- api/services/company/src/providers/CompanyRepositoryProvider.ts
- api/services/policy/src/engine/rules/inseeFilter.ts
- api/services/trip/package.json
- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/actions/CrosscheckAction.ts
- api/services/trip/src/actions/ListAction.ts
- api/services/trip/src/interfaces/TripPgRepositoryProviderInterface.ts
- api/services/trip/src/providers/TripPgRepositoryProvider.ts
- api/shared/common/interfaces/ResultWithPagination.ts
- api/shared/company/find.contract.ts
- dashboard/src/app/modules/stat/stat.module.ts
> Feat: trip total + stats

- api/services/user/src/providers/UserNotificationProvider.ts
* remettre le bon lien d'invitation
> Lien invitation 

- dashboard/cypress/integration/integration.ts
- dashboard/cypress/support/apiValues/expectedTemplates.ts
- dashboard/cypress/support/reusables/campaign/cypress_campaign_create_from_template.ts
- dashboard/cypress/support/stories/territory.story.ts
- dashboard/cypress/support/stubs/campaign/campaign-template.list.ts
- dashboard/src/app/modules/campaign/services/campaign-formating.service.ts
- dashboard/src/app/modules/company/services/company.service.ts
* syncro des templates par rapport aux models définit dans le tableur.
* mise à jour des tests
> Mise à jour des tests des templates

- api/services/policy/src/providers/CampaignPgRepositoryProvider.ts
**BACK**
* corrections des methodes de repository policy : deleteDraftAndTemplate & patch.
> Corrections - suppression & lancement de campagne

- dashboard/src/app/core/interfaces/trip/tripInterface.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.html
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
- dashboard/src/app/modules/trip/services/trip.service.ts
* afficher le total renvoyé par l'api
> Afficher en front le total calculé en back 

- api/services/user/src/providers/UserNotificationProvider.ts
fix #487 : emmettre une 404 depuis le backend
> affichage email non valide oubli de mot de passe

- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/yarn.lock
Erreur lié au numéro de Siret sur les formulaires opérateur et territoire
> Regression des form opérateur / territoire

- api/services/trip/src/providers/TripPgRepositoryProvider.ts
- dashboard/cypress/support/generators/trips.generator.ts
- dashboard/src/app/core/entities/trip/trip.ts
- dashboard/src/app/core/interfaces/trip/tripInterface.ts
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
- dashboard/src/app/modules/trip/services/trip-format.service.ts
- dashboard/src/app/modules/trip/services/trip.service.ts
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
FRONT
* correction de l'affichage des incitations, campagnes et opérateurs
BACK
* datetime >> start_datetime
Autre bug fix : 
* afficher le lien pour l'envoie de l'email d'invitation pour les utilisateurs avec le statut 'invited'
> Correction affichage des trajets

- api/proxy/src/Kernel.ts
- api/proxy/src/commands/GeoFetchCommand.ts
```shell
┌─────────┬────────┐
│  Start  │ 24774  │
│  End    │  451   │ <-- missing forever ;(
│  Found  │ 24323  │
└─────────┴────────┘
```
> geo:fetch command

- api/package.json
- api/proxy/package.json
- api/proxy/src/HttpTransport.ts
- api/proxy/src/Kernel.ts
- api/scalingo/stats-refresh.js
- api/services/mongostats/.gitignore
- api/services/mongostats/package.json
- api/services/mongostats/src/ServiceProvider.ts
- api/services/mongostats/src/actions/ListAction.ts
- api/services/mongostats/src/bootstrap.ts
- api/services/mongostats/src/config/connections.ts
- api/services/mongostats/src/config/mongostats.ts
- api/services/mongostats/src/interfaces/MongostatsRepositoryProviderInterface.ts
- api/services/mongostats/src/providers/MongoStatsRepositoryProvider.ts
- api/services/mongostats/tsconfig.json
- api/yarn.lock
> Mongo Statistics

- api/scalingo/stats-refresh.js
sort by `created_at` and find latest based on that.
> fix stats processor

- dashboard/cypress/support/stories/territory.story.ts
- dashboard/src/app/modules/campaign/pages/campaign-draft-view/campaign-draft-view.component.ts
- dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.html
* téléphone >> numéro de téléphone
* message pour dire que le lancement de la campagne n'est pas possible actuellement
> Blocker lancement campagne, correction ux

- api/shared/common/interfaces/CompanyInterface.ts
- dashboard/src/app/core/entities/operator/operator.ts
- dashboard/src/app/modules/company/services/company.service.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list-view/operator-list-view.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list-view/operator-list-view.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.ts
- correction l'algo de génération de TVA (prefix avec un zero)
- correction de regression sur le form territory
- envois de l'objet company préremply lors de l'update de territory / operator : (l'API ne récupérant pas les informations des société sur base du siret)
> Correctif TVA

- api/db/migrations/20191130003916-carpool-idx.js
- api/db/migrations/carpool/20191130003916_create_unique_index.down.sql
- api/db/migrations/carpool/20191130003916_create_unique_index.up.sql
- api/db/migrations/trip/20191125100001_create_trip_view.up.sql
- api/services/acquisition/src/config/ajv.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- api/services/user/src/actions/MeUserAction.ts
- dashboard/src/app/core/entities/authentication/user.ts
- dashboard/src/app/core/services/store/crud-store.ts
- dashboard/src/app/modules/filter/services/filter.service.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
suppression des permissions lors de la creation d'utilisateurs
> Correctif creation des utilisateurs

- api/services/trip/src/actions/StatsAction.ts
- dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.ts
Erreur front quand l'utilisateur connecté n'a pas de numéro de téléphone
> Correction formulaire profile

- api/db/migrations/trip/20191125100001_create_trip_view.up.sql
- api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- api/services/user/src/templates/confirm_email.hbs
- api/services/user/src/templates/email_changed.hbs
- api/services/user/src/templates/forgotten_password.hbs
- api/services/user/src/templates/invite.hbs
- api/shared/user/changePassword.contract.ts
- api/shared/user/common/interfaces/UserCreateInterface.ts
- api/shared/user/common/interfaces/UserFindInterface.ts
- api/shared/user/common/interfaces/UserFullInterface.ts
- api/shared/user/common/interfaces/UserInterface.ts
- api/shared/user/common/interfaces/UserListInterface.ts
- api/shared/user/common/interfaces/UserStatusInterface.ts
- api/shared/user/create.contract.ts
- api/shared/user/find.contract.ts
- dashboard/cypress/integration/integration.ts
- dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
- dashboard/src/app/core/entities/api/jsonRPCParam.ts
- dashboard/src/app/core/entities/authentication/user.ts
- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- dashboard/src/app/modules/authentication/pages/reset-forgotten-password/reset-forgotten-password.component.ts
- dashboard/src/app/modules/user/services/user-api.service.ts
- dashboard/src/app/modules/user/services/user-store.service.ts
- nettoyage dans les interfaces communes
- implémentation des interfaces dans les actions front
- mise à jour des action / params pour rendre les parametre / résultat typable
> Nettoyage des interfaces partagées

- dashboard/src/app/core/services/api/json-rpc.service.ts
* supprimer le redirection vers login qu'en on catche des 401 suite à un post
> Supprimer les redirections des erreurs de permissions en post vers login

- api/services/user/src/actions/CreateUserAction.ts
- api/services/user/src/actions/PatchUserAction.ts
- api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- dashboard/src/app/core/services/store/crud-store.ts
- dashboard/src/app/modules/administration/pages/users/users.component.html
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
- dashboard/src/app/modules/user/services/user-api.service.ts
> Correctif front / bac kpré mise en prod

- dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
Test sur les filtres : insees >> insee
> Correction test cypress

- dashboard/src/app/core/components/dialog/confirm-dialog.component.ts
- dashboard/src/app/core/services/dialog.service.ts
- dashboard/src/app/modules/administration/pages/all-users/all-users.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.ts
- dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.ts
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.scss
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
* ajout des noms des opérateurs & territoires dans liste côté registre
* utilisation de mat-icon pour les actions sur les utilisateurs
* mise à jour de la couleur de confirmation d'une action de suppression ( 'warn' )
> Ajouter noms des opérateurs & territoires sur la liste des utilisateurs

- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.ts
* bouton suppression dans le tableau des opérateurs
* utilisation de mat-icon
> Ajouter l'action de suppression d'un opérateur dans l'interface admin

- .circleci/config.yml
- api/providers/notification/src/Notification.ts
- api/providers/notification/src/mail/MailjetDriver.ts
- api/proxy/src/HttpTransport.ts
- api/services/territory/src/actions/ListTerritoryOperatorAction.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- dashboard/src/app/core/interfaces/stat/StatInterface.ts
- dashboard/src/app/modules/stat/config/stat.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-number/stat-number.component.html
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.ts
- dashboard/src/app/modules/stat/services/stat-format.service.ts
> MAJ staging

- dashboard/cypress/support/expectedApiPayload/expectedApplication.ts
- dashboard/cypress/support/reusables/operator/application.cypress.ts
- dashboard/cypress/support/stubs/operator/application/application.revoke.ts
- dashboard/src/app/modules/operator/services/application.service.ts
* corriger le test cypress de la suppression d'une application
> Correction de cypress

- api/services/policy/src/engine/helpers/faker.ts
- api/services/policy/src/engine/rules/idfm.spec.ts
- api/services/policy/src/engine/rules/idfm.ts
- api/services/policy/src/interfaces/PersonInterface.ts
- api/services/policy/src/providers/TripRepositoryProvider.ts
- api/services/policy/tests/templates/nonFinancialIncentivePolicy.spec.ts
* add idfm policy
* add unit test on idfm policy
* add territory_id in order to provide simpler filter
> IDFM policy

- api/services/user/src/actions/NotifyUserAction.ts
- api/services/user/src/providers/UserNotificationProvider.ts
fix #721 : mail de bienvenue utilise le mauvais template
> Correctif template email id

- api/services/operator/src/actions/FindOperatorAction.ts
- api/services/operator/src/providers/OperatorPgRepositoryProvider.ts
- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- api/services/user/src/actions/CreateUserAction.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- dashboard/src/app/core/entities/operator/operator.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/modules/territory/services/territory-api.service.ts
- Appel des fonctions fetch / found de companie lors de la création / mis à jours des territoires / opérateurs.
- Détection des collisions de Siret entre territoire
- Correctif de la création d'opérateur (bug champs nom)
- Correctif du bug de collision d'email lors de la création d'utilisateur.
> Service Company <> Territoire / Opérateur

- dashboard/src/app/modules/filter/components/filter/filter.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
- dashboard/src/app/modules/territory/services/territory-api.service.ts
#726 filtrage des dropdowns sur base des opérateur visible par un territoire
> filtre incohérent pour le opérateur non visible

- api/services/trip/src/providers/StatCacheRepositoryProvider.ts
> hotfix(trip): fix stat date selector

- api/services/trip/src/providers/TripRepositoryProvider.ts
- dashboard/cypress/support/expectedApiPayload/expectedCampaign.ts
- dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
- dashboard/src/app/core/const/days.const.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.ts
- dashboard/src/app/modules/filter/components/filter/filter.component.ts
Mise à jour la norme des jours de la semaine.
cf : #704
> Norme des jours de la semaine

- dashboard/src/app/core/const/validators.const.ts
- dashboard/src/app/core/entities/operator/operator.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/shared/modules/form/components/form-bank/form-bank.component.html
- dashboard/src/app/shared/modules/form/forms/form-bank.ts
- dashboard/src/app/shared/modules/form/validators/bic.validator.ts
- dashboard/src/app/shared/modules/form/validators/iban.validator.ts
- valeurs non envoyés au backend
- règle de validation iban pas assez restrictive
- règle de validation bic pas assez restrictive
fix #737
> Correctif problème du formulaire opérateur / banque

- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/modules/administration/pages/operator-visibility/operator-visibility.component.html
- dashboard/src/app/modules/authentication/modules/change-password/components/change-password/change-password.component.html
- dashboard/src/app/modules/authentication/modules/change-password/components/change-password/change-password.component.ts
- dashboard/src/app/modules/filter/components/filter/filter.component.html
- dashboard/src/app/modules/filter/components/filter/filter.component.ts
- dashboard/src/app/modules/filter/validators/date-range.validator.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.scss
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.html
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.scss
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list/territory-list.component.scss
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.scss
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html
- dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.scss
Issues #756 
* redirection page accueil
* masquer les champs mdp dans la page profil
* tooltip opérateur non visible 
* positionnement des icônes
* bouton mise à jour de l'opérateur 
* ajouter de détails pour une meilleurs compréhension de la partie visibilité
* validation sur les dates des filtres
#725 #730  #736 #723 #702 #752 #388
> Corrections UI 

- dashboard/src/app/modules/authentication/modules/change-password/components/change-password/change-password.component.ts
- dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.ts
Message erreur plus clair lors du change de mot de passe depuis la page profile
bug #778
> message d'erreur on profile > changement de mot de passe

- dashboard/src/app/core/services/common-data.service.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-auto-complete/campaign-auto-complete.component.ts
- dashboard/src/app/modules/campaign/services/campaign-api.service.ts
* fix de l'autocomplete campagnes pour afficher uniquement les campagnes lancés 
#779
> Clean service commondata et fix de l'autocomplete campagnes

- api/db/README.md
- api/db/migrations/20200107000000-update_policy_table.js
- api/db/migrations/policy/20200107000000-update_policy_table.down.sql
- api/db/migrations/policy/20200107000000-update_policy_table.up.sql
- api/services/policy/src/ServiceProvider.ts
- api/services/policy/src/commands/SeedCommand.ts
- api/services/policy/src/engine/template.ts
> feat(policy): add template seeder command

- dashboard/src/app/modules/authentication/layouts/change-auth-layout/change-auth-layout.component.scss
- dashboard/src/app/modules/authentication/pages/login/login.component.scss
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-retribution-view/campaign-retribution-view.component.scss
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-rules-view/campaign-rules-view.component.scss
- dashboard/src/app/modules/campaign/pages/campaign-active-view/campaign-active-view.component.ts
- dashboard/src/app/modules/campaign/pages/campaign-draft-view/campaign-draft-view.component.ts
- dashboard/src/app/modules/filter/components/filter/filter.component.html
- dashboard/src/app/modules/filter/components/filter/filter.component.scss
- dashboard/src/app/modules/filter/services/filter.service.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-operator-view/stat-operator-view.component.scss
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.scss
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.scss
- dashboard/src/app/shared/components/header/header.component.scss
- dashboard/src/index.html
- dashboard/src/styles/inputs.scss
- dashboard/src/styles/variables.scss
Fix sur edge 18 
* loader
* width de mat-field
* flex avec space-evenly
* champ input 'time'
* supprimer les scrollTo()
> Passe front sur le navigateur Edge 18

- api/services/user/src/actions/PatchUserAction.ts
- api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- api/shared/user/common/interfaces/UserPatchInterface.ts
- api/shared/user/patch.schema.ts
- dashboard/src/app/core/entities/authentication/user.ts
- dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
Possibilité de changé le rôle d'un utilisateur depuis l'interface d'admin.
#660
> Possibilité de changer le rôle d'utilisateur

- api/services/user/src/config/permissions.ts
- dashboard/src/app/core/services/common-data.service.ts
- dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts
- dashboard/src/app/modules/administration/administration-routing.module.ts
- dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.html
- dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.ts
sur base du document 
https://docs.google.com/spreadsheets/d/11lpQvGaUdRMnotO9Oj4kYxi5k5vdhg_wTaomH4i6MEk/edit#gid=0
#660
> Mise en conformité du mode consultation

- dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
- dashboard/src/app/modules/campaign/campaign.module.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/campaign-ui.module.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-table/campaign-table.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-table/campaign-table.component.ts
- dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.html
- dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.scss
- dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.ts
#668 
- ajout de la pagination
- utilisation d'un tableau angular
- afficher le nom du territoire
> Afficher nom territoire dans la liste des campagnes

- dashboard/src/app/core/enums/campaign/incentive-unit.enum.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-rules-view/campaign-rules-view.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-rules-view/campaign-rules-view.component.scss
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-rules-view/campaign-rules-view.component.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.ts
- dashboard/src/app/modules/campaign/services/campaign-ui.service.ts
- dashboard/src/app/modules/filter/components/filter/filter.component.html
Les issues suivantes sont fixés : 
#784
#732
#746
#787
> Corrections UI sur les campagnes

- dashboard/src/app/shared/modules/form/components/form-bank/form-bank.component.ts
- dashboard/src/app/shared/modules/form/forms/form-bank.ts
- dashboard/src/app/shared/modules/form/validators/bic.validator.ts
- dashboard/src/app/shared/modules/form/validators/iban.validator.ts
Correction de la validation du bic et iban quand la valeur est null.
> Correction formulaire opérateur

- dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.html
Some view rules not working (ng serve / ng build check differenties)
> fix - campaign list regression

- dashboard/src/app/core/entities/campaign/api-format/campaign.formater.ts
- dashboard/src/app/core/entities/campaign/ux-format/campaign-ux.ts
- dashboard/src/app/core/interfaces/campaign/api-format/campaign-global-rules.interface.ts
- dashboard/src/app/core/interfaces/campaign/ux-format/campaign-ux.interface.ts
- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-3/parameters-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/step-3/parameters-form.component.scss
- dashboard/src/app/modules/campaign/services/campaign-ui.service.ts
- Add new optional rule passenger seat
- Implement campaign edit/create form checkbox
#713
> campaign add passenger seat checkbox in params form

- dashboard/src/app/modules/campaign/services/campaign-ui.service.ts
> Correctif de texte récapitulatif de campagne

- dashboard/src/index.html
- dashboard/src/main.ts
Detection d'IE 11- et affichage d'une bannière de non compatibilité.
fix #797
> Detection internet explorer 11

- api/services/trip/src/providers/TripRepositoryProvider.ts
- api/yarn.lock
lors de la recherche de trip par code Insee tous les autres filtres (notamment territoire) sont ignorés.
> Correctif filtre part code insee

- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.html
> Correctif formulaire campagne operateur

- api/.env.example
- api/db/README.md
- api/proxy/mocha/auth.spec.ts
- api/services/application/tests/ApplicationPgRepositoryProvider.spec.ts
- api/services/carpool/src/providers/CarpoolRepositoryProvider.spec.ts
- api/services/carpool/src/providers/CrosscheckRepositoryProvider.spec.ts
- api/services/carpool/src/providers/IdentityRepositoryProvider.spec.ts
- api/services/certificate/tests/CarpoolPgRepositoryProvider.spec.ts
- api/services/operator/tests/OperatorPgRepositoryProvider.spec.ts
- api/services/policy/src/engine/meta/MetadataProvider.spec.ts
- api/services/policy/src/providers/CampaignRepositoryProvider.spec.ts
- api/services/policy/src/providers/IncentiveRepositoryProvider.spec.ts
- api/services/policy/src/providers/TripRepositoryProvider.spec.ts
- api/services/territory/src/providers/TerritoryOperatorRepositoryProvider.spec.ts
- api/services/user/tests/AuthRepositoryProvider.spec.ts
- api/services/user/tests/UserPgRepositoryProvider.spec.ts
- docker-compose.yml
- docker/postgres/Dockerfile
- PostgreSQL 12
- Postgis 2.5
à faire en local pour la mise à jour (perte des données)
en supposant que la base de données dans `.env` s'appelle `local`.
```shell
sudo mv db/postgres db/postgres-11
cd api
docker-compose build postgres
docker-compose up -d postgres
psql -d postgres
> CREATE DATABASE local;
> \q
docker-compose run api yarn migrate
```
pour importer un dump de `dev` ou `staging` qui sont en version 12.
```shell
tar xvzf 202004...tar.gz
psql -d postgres
> CREATE DATABASE local;
> \q
pg_restore -O -x -d ppcc 202004...pgsql
```
Il faut mettre à jour les clients PostgreSQL en local si vous les utilisez (`psql`, ...).
Sur Ubuntu
```shell
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
echo "deb http://apt.postgresql.org/pub/repos/apt/ …
```
> Upgrade PostgreSQL

- api/.env.example
- api/providers/file/package.json
- api/providers/file/src/FFSendStorageProvider.ts
- api/providers/file/src/S3StorageProvider.ts
- api/providers/file/src/index.ts
- api/proxy/src/HttpTransport.ts
- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/actions/BuildExportAction.ts
- api/services/trip/src/config/email.ts
- api/services/trip/src/config/notification.ts
- api/services/user/src/config/template.ts
- api/services/user/src/templates/export_csv.hbs
- api/services/user/src/templates/export_csv_error.hbs
- api/yarn.lock
- dashboard/src/app/app-routing.module.ts
- dashboard/src/app/core/components/service-unavailable/service-unavailable.component.html
- dashboard/src/app/core/components/service-unavailable/service-unavailable.component.scss
- dashboard/src/app/core/components/service-unavailable/service-unavailable.component.ts
- dashboard/src/app/core/core.module.ts
- dashboard/src/app/core/interceptor/http.interceptor.ts
- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.html
- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.scss
- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.ts
> Upload des exports sur S3

- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/actions/SearchCountAction.ts
- api/services/trip/src/interfaces/TripRepositoryProviderInterface.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- dashboard/src/app/core/const/filter.const.ts
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.html
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
- dashboard/src/app/modules/trip/services/trip-api.service.ts
- dashboard/src/app/modules/trip/services/trip-store.service.ts
- dashboard/src/app/modules/trip/trip.module.ts
- shared/trip/searchcount.contract.ts
- shared/trip/searchcount.schema.ts
Utilisation de la pagination
Optimisation du comptage du total.
Perfs à améliorer sur le front.
> Fix lazyloading

- api/providers/sentry/src/SentryProvider.ts
- api/proxy/src/HttpTransport.ts
- api/proxy/src/config/sentry.ts
- dashboard/src/environments/environment.ts
- Utilisation du tag git pour le nom de la release Sentry.
- Désactivation des erreurs remontant de localhost (configuration dans l'interface de Sentry)
- Connexion du repo Github à https://sentry.data.gouv.fr
Les erreurs sont catégorisées par `servername`, `environment` (`local`, `dev`, `staging`, `production`).
A définir : 
- stratégie de gestion des erreurs entre Github et Sentry
- notifications (Slack, Desktop Notifications, etc)
https://github.blog/2020-08-24-automate-releases-and-more-with-the-new-sentry-release-github-action/
https://docs.sentry.io/product/releases/
A voir :
https://docs.sentry.io/product/sentry-basics/guides/integrate-frontend/configure-scms/
https://docs.sentry.io/product/error-monitoring/issue-owners/
> Customisation de la release Sentry

- api/db/migrations/20200909142005-add_france_country.js
- api/db/migrations/territory/20200909142005_add_france_country.down.sql
- api/db/migrations/territory/20200909142005_add_france_country.up.sql
- api/proxy/src/commands/SyncRegionDepCommand.ts
- Ajout du pays France
- Lien avec les régions
fix #998
> Ajouter le pays "France" comme parent des régions

- api/ilos/handler-redis/src/QueueHandler.ts
- api/proxy/src/HttpTransport.ts
- api/services/monitoring/src/commands/JourneysStatsCommand.ts
- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/cron/TripCacheWarmCron.ts
- api/services/user/src/ServiceProvider.ts
- api/services/user/src/actions/HasUsersAction.ts
- api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- dashboard/src/environments/environment.ts
- shared/trip/cacheWarmCron.contract.ts
- shared/user/hasUsers.contract.ts
Petit CRON de warmup pour `trip:stats` tous les matins.
> Warm trip stats cache at 5:17 every morning

- api/providers/middleware/src/ChannelService/ChannelServiceBlacklistMiddleware.ts
- api/providers/middleware/src/ChannelService/ChannelServiceWhitelistMiddleware.ts
- api/services/operator/src/actions/DeleteOperatorAction.ts
- api/services/territory/src/actions/DeleteTerritoryAction.ts
- api/services/user/src/ServiceProvider.ts
- api/services/user/src/actions/DeleteAssociatedUserAction.ts
- api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- shared/user/deleteAssociated.contract.ts
- shared/user/deleteAssociated.schema.ts
fix #945
Soft delete sur les territoires et les opérateurs mais PAS sur les utilisateurs !
> Suppression des utilisateurs associés

- api/db/migrations/territory/20200406000000_update_territory_table.up.sql
- api/db/migrations/territory/20200406000001_migrate_territory_data.up.sql
- api/db/migrations/territory/20200606000004_clean_territory_names.up.sql
- api/services/policy/src/engine/rules/filters/TimeRangeFilter.ts
- api/services/policy/src/engine/rules/filters/WeekdayFilter.ts
- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/actions/ListAction.ts
- api/services/trip/src/actions/StatsAction.ts
- dashboard/src/app/core/entities/territory/territory.ts
- dashboard/src/app/core/services/sentry-error-handler.service.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-children/territory-children.component.ts
- dashboard/src/index.html
- Correction des exceptions sentry (handlerError)
- Correction contenu langue html, google translate retraduit en français 
- Suppression du niveau Epic et conversation vers towngroup pour les territoires
- Correctif lint
- Correction front ajout d'un territoire enfant qui n'a lui même pas d'enfant
> Correctif front

- api/db/migrations/20200929085044-add-last-login.js
- api/db/migrations/auth/20200929085044_add_last_login.down.sql
- api/db/migrations/auth/20200929085044_add_last_login.up.sql
- api/services/user/src/ServiceProvider.ts
- api/services/user/src/actions/LoginUserAction.ts
- api/services/user/src/commands/FindInactiveCommand.ts
- api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
- api/services/user/src/providers/UserPgRepositoryProvider.ts
- shared/user/common/interfaces/UserLastLoginInterface.ts
> Listing des utilisateurs inactifs

- api/services/territory/src/interfaces/TerritoryRepositoryProviderInterface.ts
- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- api/services/trip/src/actions/BuildExportAction.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-children/territory-children.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-selection-block/territory-selection-block.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-selection-group/territory-selection-group.component.ts
- dashboard/src/app/modules/territory/services/territory-api.service.ts
- shared/territory/TerritoryUIFormatEnum.ts
- shared/territory/TerritoryUIStatus.ts
- shared/territory/TerritoryUiStatusSelectionState.ts
- shared/territory/TerritoryUiStatusSelectionStateEnum.ts
- shared/territory/parentChildren.contract.ts
- define interfaces for ui_status
- fix getDirectRelation in order to get all results
- implement getDirectRelation impact on front API client
> Territory Provider clean

- api/db/migrations/territory/20200606000001_create_territory_view_data_func.up.sql
> Fix missing foreign country names

- api/proxy/src/HttpTransport.ts
- api/services/territory/src/ServiceProvider.ts
- api/services/territory/src/actions/DropdownTerritoryAction.ts
- api/services/territory/src/actions/ListTerritoryAction.ts
- api/services/territory/src/interfaces/TerritoryRepositoryProviderInterface.ts
- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
- dashboard/src/app/modules/territory/services/territory-api.service.ts
- shared/territory/common/interfaces/TerritoryDropdownInterface.ts
- shared/territory/dropdown.contract.ts
- shared/territory/dropdown.schema.ts
- shared/territory/list.schema.ts
> Filter territory dropdown

- api/db/migrations/20200930205639-add-company-fields.js
- api/db/migrations/company/20200930205639_add_fields.down.sql
- api/db/migrations/company/20200930205639_add_fields.up.sql
- api/services/company/src/actions/FetchAction.ts
- api/services/company/src/providers/CompanyDataSourceProvider.ts
- api/services/company/src/providers/CompanyRepositoryProvider.ts
- dashboard/src/app/core/entities/shared/companyV2.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
- dashboard/src/app/shared/modules/form/forms/form-company.ts
- shared/common/interfaces/CompanyInterface2.ts
- shared/common/schemas/company.ts
fix #1050 
Un peu de nettoyage et d'amélioration de l'UX du formulaire.
> Fix operator creation

- dashboard/src/app/modules/administration/pages/api/api.component.html
- dashboard/src/app/modules/certificate/pages/check/check.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-operator-view/stat-operator-view.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.html
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
- dashboard/src/app/shared/components/footer/footer.component.html
- dashboard/src/app/shared/components/help-card/help-card.component.html
- dashboard/src/manual-503.html
> No woman no cry

- api/proxy/package.json
- api/proxy/src/HttpTransport.ts
- api/proxy/src/middlewares/rateLimiter.ts
- api/yarn.lock
> rate limiter

- api/ilos/common/src/exceptions/TooManyRequestsException.ts
- api/ilos/common/src/exceptions/index.ts
- api/proxy/src/HttpTransport.ts
- api/proxy/src/middlewares/errorHandlerMiddleware.ts
- api/proxy/src/middlewares/rateLimiter.ts
- api/services/company/src/providers/CompanyDataSourceProvider.ts
- dashboard/src/app/core/entities/territory/territory.ts
- dashboard/src/app/core/interceptor/http.interceptor.ts
- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-selection-block/territory-selection-block.component.ts
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- shared/territory/common/schema.ts
> fix territory creation form

- api/services/operator/src/actions/DeleteOperatorAction.ts
> revoke operator apps

- dashboard/src/app/core/entities/territory/territory.ts
- dashboard/src/app/core/guards/auth-guard.service.ts
- dashboard/src/app/core/guards/change-email-guard.service.ts
- dashboard/src/app/core/guards/login-guard.service.ts
- dashboard/src/app/core/guards/reset-password-guard.service.ts
- dashboard/src/app/core/interceptor/http.interceptor.ts
- dashboard/src/app/core/services/api/json-rpc.service.ts
- dashboard/src/app/core/services/authentication/authentication.service.ts
- dashboard/src/app/core/services/sentry-error-handler.service.ts
- dashboard/src/app/core/services/store/crud-store.ts
- dashboard/src/app/modules/authentication/pages/login/login.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-1/campaign-templates.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-3/parameters-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/step-3/parameters-form.component.ts
- dashboard/src/app/modules/campaign/components/campaign-form/step-3/restriction-form/restriction-form.component.html
- dashboard/src/app/modules/campaign/components/campaign-form/step-3/restriction-form/restriction-form.component.ts
- dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- shared/territory/common/schema.ts
> fix some front stuff

- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- dashboard/src/app/core/entities/territory/territory.ts
- dashboard/src/app/modules/territory/TerritoryQueryInterface.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-children/territory-children.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- shared/policy/create.schema.ts
- shared/territory/common/interfaces/TerritoryQueryInterface.ts
> fix territory update/create

- api/ilos/connection-redis/package.json
- api/ilos/connection-redis/src/RedisConnection.ts
- api/ilos/connection-redis/src/index.ts
- api/ilos/framework/src/tests/queue.spec.ts
- api/ilos/handler-redis/package.json
- api/ilos/handler-redis/src/QueueHandler.spec.ts
- api/ilos/handler-redis/src/QueueHandler.ts
- api/ilos/handler-redis/src/helpers/bullFactory.ts
- api/ilos/transport-redis/package.json
- api/ilos/transport-redis/src/QueueTransport.spec.ts
- api/ilos/transport-redis/src/QueueTransport.ts
- api/ilos/transport-redis/src/helpers/bullFactory.ts
- api/package.json
- api/providers/sentry/src/SentryProvider.ts
- api/providers/test/src/dbTestMacro.ts
- api/providers/test/src/fixtures/schemas.sql
- api/proxy/package.json
- api/proxy/src/QueueTransport.ts
- api/proxy/src/tests/mocks/payloadV2.ts
- api/proxy/src/tests/pipeline.spec.ts
- api/services/normalization/src/actions/NormalizationTerritoryAction.ts
- api/yarn.lock
> Fix: bull version

- dashboard/src/app/core/services/sentry-error-handler.service.ts
- dashboard/src/app/core/services/store/getlist-store.ts
- dashboard/src/app/modules/administration/pages/users/users.component.ts
- dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list-view/operator-list-view.component.ts
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
- dashboard/src/app/shared/shared.module.ts
- dashboard/src/environments/environment.ts
- fix ExpressionChangedAfterItHasBeenCheckedError on territory list
- Better debounce time on territories / operators list components
- add track error cond on sentry error handler
- no sentry config by default (no sentry debug on local)
- admin campaign list stream fixes
- fix user missing on trip list access check
- fix user list debounce for better store sync
- optimise operator visibility
- fix : filtered list sync issues
- clean campaign list interfaces
- avoid api recall by adding debounce time on filter subject
> front : Component states fixes optimisation

- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- dashboard/src/app/core/services/store/getlist-store.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.ts
- fix : undefined user on auth-> user$
- front / global debounce on store.load-list
- back : order by name on territory list
> territory list order by name + fixes

- api/ilos/framework/src/tests/queue.spec.ts
- api/ilos/transport-redis/src/QueueTransport.spec.ts
- api/proxy/src/tests/pipeline.spec.ts
- api/services/company/src/interfaces/CompanyDataSourceProviderInterface.ts
- api/services/company/src/providers/CompanyDataSourceProvider.ts
- api/services/territory/src/actions/ListTerritoryAction.ts
- api/services/territory/src/interfaces/TerritoryRepositoryProviderInterface.ts
- api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
- dashboard/src/app/core/entities/territory/territory.ts
- dashboard/src/app/core/services/common-data.service.ts
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.html
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.scss
- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.ts
- shared/territory/common/interfaces/TerritoryQueryInterface.ts
- mise sous forme de la selection opérateur territoire
- réfactoring du composant de selection (ancienne solution lente avec un nombre conséquent de territoire)
> Selection de la visibilité opérateur / territoire

- api/services/policy/src/actions/FindCampaignAction.ts
- dashboard/src/app/core/entities/shared/contact.ts
- dashboard/src/app/core/entities/utils.ts
- dashboard/src/app/modules/campaign/campaign-routing.module.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-table/campaign-table.component.html
- dashboard/src/app/modules/campaign/pages/campaign-draft-view/campaign-draft-view.component.html
- dashboard/src/app/modules/campaign/pages/campaign-draft-view/campaign-draft-view.component.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph-view/stat-graph-view.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph-view/stat-graph-view.component.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph.component.ts
- dashboard/src/app/modules/stat/services/stat-filtered-store.service.ts
- Correction des incohérence dans le graphique stats : https://github.com/betagouv/preuve-covoiturage/issues/1107
- Prévisualisation des campagnes depuis l'espace registre : https://github.com/betagouv/preuve-covoiturage/issues/993
> Correctif UI :  stats et campagne 

- api/providers/middleware/package.json
- api/providers/middleware/src/ContextExtract/ContextExtractMiddleware.ts
- api/providers/middleware/src/index.ts
- api/services/policy/src/ServiceProvider.ts
- api/services/policy/src/actions/CreateCampaignAction.ts
- api/services/policy/src/actions/DeleteCampaignAction.ts
- api/services/policy/src/actions/FindCampaignAction.ts
- api/services/policy/src/actions/TemplatesCampaignAction.ts
- api/services/policy/src/providers/CampaignPgRepositoryProvider.ts
- shared/policy/find.schema.ts
> fix campaign:find mw

- dashboard/angular.json
- dashboard/package.json
- dashboard/src/app/modules/administration/administration.module.ts
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-list.component.html
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-list.component.ts
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-meta-dialog/certificate-meta-dialog.component.html
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-meta-dialog/certificate-meta-dialog.component.scss
- dashboard/src/app/modules/administration/pages/certificate-list/certificate-meta-dialog/certificate-meta-dialog.component.ts
- dashboard/src/app/modules/certificate/services/certificate-api.service.ts
- dashboard/src/app/shared/modules/material/material.module.ts
- dashboard/yarn.lock
- Fix des liens de téléchargement des attestations PDF
- Ajout d'une modale pour remplir les champs de meta-données (opérateur, identité, notes)
> Ajout de meta-données aux attestations pour les super-admin

- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.ts
Correctif de l'erreur de conversation centime > euro du budget campagne
> fix #1128 : correctif Erreur dans les budgets campagnes

- dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.ts
mise à jour de l'état de la selection de tous les opérateurs quand ceux-ci sont sélectionné dans l'interface.
> fix 1139 : bug selection de tous les opérateurs

- api/services/user/src/templates/export_csv.hbs
fix trip export link in email template
> hotfix export link

- api/services/company/src/providers/CompanyDataSourceProvider.ts
- api/services/policy/src/middlewares/ValidateDateMiddleware.ts
- dashboard/src/app/core/entities/campaign/api-format/campaign.formater.ts
- dashboard/src/app/modules/campaign/services/campaign-ui.service.ts
Correction des erreurs d'affichages sur les dates de début et de fin en utilisant les bons fuseaux horaires.
> Campagne affichage des date de début de fin

- dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.ts
- dashboard/tsconfig.json
Changement de la limite de recherche dans le dropdown de recherche des villes (création de campagnes, étape 2).
> [hotfix] bump results limit to 100 on town search

- dashboard/src/app/core/services/store/crud-store.ts
- dashboard/src/app/modules/administration/pages/territory/territory.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list-view/operator-list-view.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.html
- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.ts
> fix nav btw list / form in territories and operators

- api/services/user/src/templates/confirm_email.hbs
- api/services/user/src/templates/email_changed.hbs
- api/services/user/src/templates/forgotten_password.hbs
- api/services/user/src/templates/invite.hbs
> Boutons dans les emails

- api/providers/file/src/S3StorageProvider.ts
- api/providers/notification/src/Notification.ts
- api/providers/notification/src/interfaces/SendOptionsInterface.ts
- api/providers/notification/src/interfaces/index.ts
- api/providers/notification/src/mail/MailjetDriver.ts
- api/services/trip/src/actions/BuildExportAction.ts
- api/services/user/src/actions/NotifyUserAction.ts
MJ ne connait pas encore le HTTPS... _stay safe and disable tracking !_
> disable mailjet tracking on export emails

- api/ilos/connection-postgres/src/PostgresConnection.ts
- api/services/company/src/providers/CompanyDataSourceProvider.ts
> API entreprise v3

- dashboard/angular.json
- dashboard/tsconfig.app.json
Suppression des restes de config `leaflet` utilisés dans des composants front supprimés.
> remove leaflet

- api/db/migrations/20210329000000-update_acquisition_carpool_view.js
- api/db/migrations/acquisition/20210329000000_update_acquisition_carpools.down.sql
- api/db/migrations/acquisition/20210329000000_update_acquisition_carpools.up.sql
- api/services/acquisition/src/actions/CancelJourneyAction.ts
- api/services/acquisition/src/actions/StatusJourneyAction.ts
- api/services/acquisition/src/interfaces/CarpoolRepositoryProviderInterface.ts
- api/services/acquisition/src/interfaces/ErrorRepositoryProviderInterface.ts
- api/services/acquisition/src/interfaces/JourneyRepositoryProviderInterface.ts
- api/services/acquisition/src/providers/CarpoolRepositoryProvider.ts
- api/services/acquisition/src/providers/ErrorPgRepositoryProvider.ts
- api/services/acquisition/src/providers/JourneyPgRepositoryProvider.ts
> Réparer la route status

- README.md
Ajout d'un header unifié à dupliquer sur les différents dépôts.
> Ajout d'un header unifié au Readme

- api/proxy/src/HttpTransport.ts
Ajout de la route publique `/honor/stats`
lié à #818
Réponse au format JsonRPC :
```json
{
"id": 1,
"result": {
"meta": null,
"data": {
"labels": ["2020-10-23", "2020-10-27", "2020-10-28", "2020-10-29", "2020-10-30", "2020-10-31", "2020-11-01", "2020-11-02", "2020-11-03", "2020-11-04", "2020-11-05", "2020-11-06", "2020-11-07", "2020-11-08", "2020-11-09", "2020-11-10", "2020-11-11", "2020-11-12", "2020-11-13", "2020-11-14", "2020-11-15", "2020-11-16", "2020-11-17", "2020-11-18", "2020-11-19", "2020-11-20", "2020-11-21", "2020-11-22", "2020-11-23", "2020-11-24", "2020-11-25", "2020-11-26", "2020-11-27", "2020-11-28", "2020-11-29", "2020-11-30", "2020-12-01", "2020-12-02", "2020-12-03", "2020-12-04", "2020-12-05", "2020-12-06", "2020-12-07", "2020-12-08", "2020-12-09", "2020-12-10", …
```
> Exposer les stats des attestations sur l'honneur

- dashboard/src/app/core/const/main.const.ts
- dashboard/src/app/core/const/tooltips.const.ts
- dashboard/src/app/core/services/common-data.service.ts
- dashboard/src/app/modules/authentication/pages/login/login.component.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-table/campaign-table.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-table/campaign-table.component.ts
- dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.ts
- dashboard/src/app/modules/filter/components/filter/filter.component.ts
- dashboard/src/app/modules/operator/modules/operator-ui/components/operators-checkboxes/operators-checkboxes.component.html
- dashboard/src/app/modules/operator/modules/operator-ui/components/operators-checkboxes/operators-checkboxes.component.scss
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.html
- dashboard/src/app/shared/components/header/header.component.html
- dashboard/src/app/shared/components/header/header.component.ts
- dashboard/src/app/shared/directives/button-href.directive.ts
- dashboard/src/app/shared/shared.module.ts
- dashboard/src/styles.scss
Quelques fixes d'interface :
le reste du #1325 sera sur une autre PR
> Fixes d'interface

- dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
- dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.scss
- dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.ts
> Plage de simulation des campagnes

- api/services/policy/src/actions/LaunchCampaignAction.ts
- api/services/policy/src/interfaces/CampaignRepositoryProviderInterface.ts
- api/services/policy/src/providers/CampaignPgRepositoryProvider.ts
- dashboard/src/app/modules/campaign/pages/campaign-view/campaign-view.component.html
- dashboard/src/app/modules/campaign/pages/campaign-view/campaign-view.component.ts
https://github.com/betagouv/preuve-covoiturage/issues/1340#issuecomment-832821225
> Vérification de l'expiration d'une campagne à son lancement

- api/services/trip/src/providers/TripRepositoryProvider.ts
> fix: stat number for average carpooler by car

- api/services/user/src/notifications/ContactFormNotification.ts
- api/services/user/src/providers/UserNotificationProvider.ts
fix https://github.com/betagouv/preuve-covoiturage-vitrine/issues/27
> Suppression du sujet dans le template d'email de contact

- dashboard/src/app/core/const/main.const.ts
- dashboard/src/app/modules/administration/pages/api/api.component.html
- dashboard/src/app/modules/administration/pages/api/api.component.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-operator-view/stat-operator-view.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-operator-view/stat-operator-view.component.ts
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.ts
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
- dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.ts
- dashboard/src/app/modules/trip/pages/trip-import/trip-import.component.html
- dashboard/src/app/modules/trip/pages/trip-import/trip-import.component.ts
- dashboard/src/app/shared/components/footer/footer.component.html
- dashboard/src/app/shared/components/header/header.component.ts
Mise à jour des liens externes et refacto de leurs noms de variables.
:warning: sur la page stats publiques qui a bougé récemment.
> Mise à jour des liens de documentation

- api/services/carpool/src/providers/IdentityRepositoryProvider.ts
- shared/carpool/finduuid.schema.ts
- shared/certificate/create.schema.ts
- shared/common/schemas/findIdentity.ts
> Hotfix - création d'attestation

- api/services/carpool/src/providers/IdentityRepositoryProvider.ts
- shared/carpool/finduuid.schema.ts
- shared/certificate/create.schema.ts
- shared/common/schemas/findIdentity.ts
cherry-picking du hotfix fait sur la `release/v2.3.4`
> fix cert.create schema

- api/proxy/src/HttpTransport.ts
See related expected params from action `CreateCertificateAction` => https://github.com/betagouv/preuve-covoiturage/blob/bc821f04eed36003e3b5741a8308c08e46dfea78/shared/certificate/create.contract.ts#L5
> fix(HttpTransport): fix missing optional parameters in REST layer

- dashboard/src/app/core/interfaces/campaign/api-format/campaign-global-rules.interface.ts
fix secure randomness in CodeQL
> secure random number generation

- dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
- dashboard/src/app/modules/trip/pages/trip-import/trip-import.component.html
- dashboard/src/app/modules/ui-guide/ui-guide.component.html
Pour valider, voir les modifs dans les fichiers https://github.com/betagouv/preuve-covoiturage/pull/1499/files
> MAJ lien de doc

- api/proxy/load/README.md
- api/services/trip/src/providers/TripRepositoryProvider.ts
- #1470
- fix README file for load testing
> fix: use coalesce for subsidized to prevent null value to fail count

- api/ilos/core/src/foundation/Kernel.ts
- api/providers/middleware/README.md
- api/services/trip/src/cron/TripCacheWarmCron.ts
- doc/docs/api/licenses-list.md
- doc/docs/contribuer/api/providers/middleware/index.md
- ajout de la config du timeout de l'appel dans le contexte avec `metadata.timeout`
- fix des appels et des permissions de `trip:cacheWarmCron`
- support du `group_by` et de `tz`
- utilisation de l'image `postgis/postgis:12-2.5-alpine` pour debugguer le e2e
> Fix de la génération nocturne des statistiques

- api/providers/middleware/src/HasPermissionByScope/HasPermissionByScopeMiddleware.spec.ts
- api/proxy/src/HttpTransport.ts
- api/services/territory/src/ServiceProvider.ts
- api/services/territory/src/actions/DropdownTerritoryAction.ts
- api/services/territory/src/actions/GetAuthorizedCodesAction.ts
- api/services/trip/src/actions/excel/build/BuildFilepath.spec.ts
- api/services/trip/src/cron/TripCacheWarmCron.ts
- api/services/trip/src/middleware/ScopeToGroupMiddleware.spec.ts
- api/services/trip/src/middleware/ScopeToGroupMiddleware.ts
- api/services/trip/src/middleware/groupPermissionMiddlewaresHelper.ts
- shared/territory/getAuthorizedCodes.contract.ts
- shared/territory/getAuthorizedCodes.schema.ts
- shell.nix
- accept code types array in authorized territories middlewares
> fix: update authorized territories middleware

- api/services/trip/src/providers/TripRepositoryProvider.ts
- dashboard/src/app/core/services/store/getlist-store.ts
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.html
- dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
- #1524 
- Message d'erreur si une erreur coté BE
J'ai également mis explicitement que les incitations étaient en €. Il faudra prévoir une façon pour le front de déterminer si les incitations sont exprimées en points ou en euros le jour ou il y aura des campagnes avec des points...
> Fix incentive for trip list view

- api/services/territory/src/providers/GeoRepositoryProvider.ts
- dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.ts
- shared/territory/listGeo.contract.ts
Fix du bug constaté ici ->  https://github.com/betagouv/preuve-covoiturage/issues/1572#issuecomment-984512162
> fix: insee blacklist/whitelist filter for campaign

- api/db/package.json
- api/yarn.lock
- docker/api/Dockerfile
- docker/api/prod/Dockerfile
- docker/cypress/Dockerfile
- docker/dashboard/Dockerfile
- docker/dashboard/prod/Dockerfile
- docker/lint/Dockerfile
- docker/postgres/Dockerfile
- shell.nix
- ajout du paquet de migration des données géographique
- mise à jour des dockerfiles
> Feat : zone import

- dashboard/src/app/core/enums/trip/trip-status.enum.ts
- dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-trip/stat-graph-trip.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
- dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
#1610
- Précision du wording des trajets incités.
- Ajout du statut `fraudcheck_error` pour les statuts de la liste de trajets
> Wording des trajets incités

- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.html
> fix: update wording for campaign dashboard

- api/services/policy/src/actions/FinalizeAction.ts
- api/services/trip/src/actions/ActiveCampaignExcelExportAction.ts
> fix: change apdf cron job to j+7 and fix campaign:finalize cron action

- dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
> fix: update only when insee form is filled, patchContact otherwise

- dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-trip/stat-graph-trip.component.html
#1610
Modification du wording "Tous les trajets" de la page de stats
> Wording trajets

- api/services/fraud/src/engine/checks/self/TheoricalDistanceAndDurationCheck.ts
fix du test quand la valeur transmise est nulle.
TODO : cherrypick sur la prod si possible
> handle null value in TheoricalDistanceAndDurationCheck

- api/services/certificate/src/providers/CarpoolPgRepositoryProvider.ts
Utilisation du montant payé par le passager ou le montant payé au conducteur à la place du coût du trajet pour les attestations.
Fix temporaire pour 1 cas d'usage en attendant de pouvoir gérer ça mieux. #1667
> Utilisation du paiement pour les attestations

- api/providers/pdfcert/src/PdfCertProvider.ts
- dashboard/src/app/app-routing.module.ts
- dashboard/src/app/modules/certificate/certificate.module.ts
- dashboard/src/app/modules/certificate/pages/check/check.component.html
fix du bug de routing de la page de validation des attestations suite aux modifications du routing du module Territoire qui est importé dans le module Certificates.
> Page de vérification des attestations

- api/services/acquisition/src/providers/ErrorPgRepositoryProvider.ts
> fix: avoid select logrequest as an error

- api/proxy/src/HttpTransport.ts
Après quelques tests une session était créé et jamais détruite pour chaque appel API par les opérateurs 
```
pdc-prod-7081.redis.dbs.scalingo.com:30793> SCAN 10
1) "491530"
2)  1) "proxy:sess:zHMZVfaikGGCblEuFOIR7sNsodBMgmja"
2) "proxy:sess:OCUyUZFw1c2UW10yYD3QlmSFJHzENi4t"
3) "proxy:sess:d8kvGQkIEpUm4OA4_D1sVbt3OViwlP1O"
4) "proxy:sess:w8xWVs2qC_qCQgNYQOm0MAn6jKlfXWgq"
5) "proxy:sess:l0IJOxlmcNu5qpzm5IQ1VIcPtnFuJghW"
6) "proxy:sess:2brVWYn-L9AEJNraChRb-bbvDzkP2M8g"
7) "proxy:sess:Y3R8GdI4kqkxNqPYPgxhAkEjI0bKiZ2w"
8) "proxy:sess:nPQD_3DJvI4dUgPc4awhnUNghpfF4Lzz"
9) "proxy:sess:_tYEAp-RfCqzgf8f5W1tiJVZIP1og--Z"
10) "proxy:sess:Wmfp27HiHhD3FBL1tvZoDy_dX-9gXc3y"
```
Taille de Redis à diminuer après le déploiement
> fix(HttpTransport): do not create session when Bearer header is present

- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.html
- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.ts
> fix(TripExport): Fix checkbox operators label for operator user

- api/services/trip/src/actions/ActiveCampaignExcelExportAction.ts
- api/services/trip/src/actions/BuildExportAction.ts
Hotfix pour ne pas avoir le même problème que ce mois-ci sur les APDFs qui sont déclenchés trop tôt
Je laisse la #1744  en TODO pour trouver une solution pérenne
> fix(exports): delay opendata and apdf export to ensure after finalized

- api/db/package.json
- api/yarn.lock
- amélioration de la précision des pays
- jeu de données 2022
> fix: update geo package

- api/providers/geo/src/providers/LocalGeoProvider.ts
This will fix issue for other countries
> fix(LocalGeoProvider): return provided arr for country not France

- api/services/trip/src/actions/ExportAction.ts
- dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.ts
> fix(ExportAction): operator can export with maxdate today

- api/services/trip/src/providers/TripRepositoryProvider.ts
> Exclude null from excluded geo count

- api/services/trip/src/actions/ListCapitalCallsAction.ts
Hotfix du filtrage des résultats de la liste des APDF quand on est opérateur
> add operator and territory filtering

- .github/workflows/analysis-test-e2e.yml
- .github/workflows/analysis-test-integration.yml
- api/services/company/src/config/dataSource.ts
- api/services/company/src/config/index.ts
- api/services/company/src/providers/CompanyDataSourceProvider.integration.spec.ts
- api/services/company/src/providers/CompanyDataSourceProvider.ts
- docker-compose.e2e.yml
- tests/cypress/integration/service-user/UserCreate.feature
J'ai rajouté la clé d'API sur scalingo. A voir si on la rajoute sur dev et démo ...
> fix(CompanyDataSourceProvider): use new insee api to get siret infos

- api/services/company/src/providers/CompanyRepositoryProvider.ts
La nouvelle API geo ne donne pas d'information géographique (normal pour un siren).
J'ai juste rajouté un check pour éviter que ça fasse une 500 sur `company:fetch`
Exemple de retour de la nouvelle API siren :
```
{
"header": {
"statut": 200,
"message": "OK"
},
"uniteLegale": {
"siren": "200069599",
"statutDiffusionUniteLegale": "O",
"dateCreationUniteLegale": "2017-01-01",
"sigleUniteLegale": null,
"sexeUniteLegale": null,
"prenom1UniteLegale": null,
"prenom2UniteLegale": null,
"prenom3UniteLegale": null,
"prenom4UniteLegale": null,
"prenomUsuelUniteLegale": null,
"pseudonymeUniteLegale": null,
"identifiantAssociationUniteLegale": null,
"trancheEffectifsUniteLegale": "21",
"anneeEffectifsUniteLegale": "2020",
"dateDernierTraitementUniteLegale": "2022-08-29T09:05:23", …
```
> fix(FetchAction): create company without lon lat if not provided

- api/providers/file/src/APDFNameProvider.ts
- api/services/trip/src/actions/ExportCapitalCallsAction.ts
- api/services/trip/src/actions/excel/BuildExcel.spec.ts
- api/services/trip/src/actions/excel/BuildExcel.ts
- api/services/trip/src/actions/excel/writer/SlicesWorkbookWriter.integration.spec.ts
- api/services/trip/src/actions/excel/writer/SlicesWorkbookWriter.ts
- api/services/trip/src/interfaces/PolicySliceStatInterface.ts
- api/services/trip/src/interfaces/SlicesInterface.ts
- api/services/trip/src/interfaces/TripRepositoryProviderInterface.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- docker-compose.yml
Les APDF n'avaient pas des montants cohérents entre le fichier généré et les infos affichées dans le tableau (et le nom du fichier).
> [hotfix] Montants des APDF

- api/providers/normalization/src/interfaces/CostNormalizerProviderInterface.ts
- api/providers/normalization/src/providers/CostNormalizerProvider.spec.ts
- api/providers/normalization/src/providers/CostNormalizerProvider.ts
- api/providers/normalization/src/providers/NormalizationProvider.ts
> fix: calc cost as sum of contribution and incitations

- api/services/policy/src/actions/StatsAction.ts
- api/services/policy/src/providers/IncentiveRepositoryProvider.ts
- api/services/trip/src/actions/ExportCapitalCallsAction.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.html
- dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-main-metrics/campaign-main-metrics.component.ts
fix sur la requête de calcul des stats qui ne prenait pas en compte les trajets sans montant passager (`join` -> `left join`).
#1761 
**TODO** lancer la génération des APDF après déploiement
```
scalingo -a pdc-prod run -d --size 2XL 'LOG_LEVEL=debug APP_DISABLE_POLICY_PROCESSING=0 APP_POSTGRES_TIMEOUT=0 APP_REQUEST_TIMEOUT=0 yarn workspace @pdc/proxy ilos call capitalcall:export -c "{\"call\":{\"user\":{}},\"channel\":{\"service\":\"trip\"}}" -p "{\"query\":{\"date\":{\"start\":\"2022-04-01T00:00:00+0200\",\"end\":\"2022-05-01T00:00:00+0200\"},\"campaign_id\":[713,249,459,766,695,656]},\"format\":{\"tz\":\"Europe\/Paris\"}}"'
scalingo -a pdc-prod run -d --size 2XL 'LOG_LEVEL=debug APP_DISABLE_POLICY_PROCESSING=0 APP_POSTGRES_TIMEOUT=0 APP_REQUEST_TIMEOUT=0 yarn workspace @pdc/proxy ilos …
```
> Hotfix APDF

- api/services/trip/src/actions/BuildExportAction.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- shared/trip/buildExport.contract.ts
- shared/trip/sendExport.contract.ts
https://github.com/betagouv/preuve-covoiturage/issues/1747
> add status column for registry and operator export only

- api/db/migrations/20221107000000-policy_add_pmgf_occitanie.js
- api/db/migrations/policy/20221107000000-policy_add_pmgf_occitanie.down.sql
- api/db/migrations/policy/20221107000000-policy_add_pmgf_occitanie.up.sql
- api/services/policy/src/engine/policies/Lannion.html.ts
- api/services/policy/src/engine/policies/Lannion.ts
- api/services/policy/src/engine/policies/Occitanie.html.ts
- api/services/policy/src/engine/policies/Occitanie.spec.ts
- api/services/policy/src/engine/policies/Occitanie.ts
- api/services/policy/src/engine/policies/Pmgf.ts
- api/services/policy/src/interfaces/engine/OperatorsEnum.ts
- dashboard/src/app/modules/campaign/pages/campaign-fundingrequests/campaign-fundingrequests.component.html
- dashboard/src/app/modules/campaign/pages/campaign-fundingrequests/campaign-fundingrequests.component.ts
DOC https://hackmd.io/rW2Px0XBRDCttk2weEAqxg?edit
Occitanie : 
- Début : 24 octobre 2022
- Fin : 30 juin 2023
- https://hackmd.io/LY5joudiSJKL3hzXteERVg
```sql
INSERT INTO policy.policies (
territory_id, start_date, end_date, name, unit, status, handler
) VALUES (
248, '2022-10-24T00:00:00+0200', '2023-06-30T00:00:00+02', '#1_occitanie_202210', 'euro', 'active', 'occitanie_2022'
);
```
:warning: Attention pour Occitanie, le selecteur territoire doit être la Région et non l'aom.
PMGF :
- Début : 2 novembre 2022
- Fin : 31 décembre 2023
- https://hackmd.io/djy06sNJROOol1TVVBC_rQ
```sql
INSERT INTO policy.policies (
territory_id, start_date, end_date, name, unit, status, handler
) VALUES (
36102, '2022-11-02T00:00:00+0100', '2023-12-31T00:00:00+0100', '#1_pmgf_202211', 'euro', 'active', …
```
> Campagnes PMGF, Lannion et Occitanie

- api/providers/normalization/src/providers/NormalizationProvider.ts
`driver.contribution` -> `passenger.contribution`
> Fix cost calculation

- api/services/trip/src/actions/ActiveCampaignExcelExportAction.ts
https://github.com/betagouv/preuve-covoiturage/issues/1901
> fix: change apdf cron to 6th

- doc/docs/operateurs/cee.md
Ajout de la doc sur la vérification du token de demande CEE.
> doc: add token documentation

- dashboard/src/app/modules/campaign/pages/campaign-view/campaign-view.component.html
- dashboard/src/app/modules/campaign/pages/campaign-view/campaign-view.component.ts
Ajout d'un filtre sur l'affichage des APDF en fonction du rôle.
> APDF uniquement pour les super-admin

- dashboard/src/app/modules/campaign/pages/campaign-view/campaign-view.component.html
- dashboard/src/app/modules/campaign/pages/campaign-view/campaign-view.component.ts
> revert APDF admin only

- api/proxy/src/HttpTransport.ts
- api/services/policy/src/actions/SimulateOnPastByGeoAction.ts
- api/services/user/src/actions/SimulatePolicyformAction.ts
- shared/user/permissions.config.ts
Fix du bug de permissions sur la simulation
> fix(permissions): fix permissions chains

- api/proxy/src/HttpTransport.ts
- api/proxy/src/middlewares/rateLimiter.ts
Modification du rate limiter de la route `/v2/journeys/:id` pour permettre plus de vérifications des trajets
> Rate limiter journeys/:id

- api/db/migrations/20221215000000-create-policy-lock.js
- api/db/migrations/policy/20221215000000_create_policy_lock_table.down.sql
- api/db/migrations/policy/20221215000000_create_policy_lock_table.up.sql
- api/services/policy/src/actions/ApplyAction.ts
- api/services/policy/src/actions/FinalizeAction.ts
- api/services/policy/src/interfaces/providers/PolicyRepositoryProviderInterface.ts
- api/services/policy/src/interfaces/providers/index.ts
- api/services/policy/src/providers/IncentiveRepositoryProvider.ts
- api/services/policy/src/providers/PolicyRepositoryProvider.integration.spec.ts
- api/services/policy/src/providers/PolicyRepositoryProvider.ts
Pour éviter les problèmes de concurrence sur le finalize quand on a plusieurs workers.
> feat: add lock system

- api/ilos/framework/src/Bootstrap.ts
> fix: log level

- api/services/cee/src/helpers/isBeforeOrFail.ts
> fix: rollback and avoid casting

- .vscode/extensions.json
- shared/certificate/common/interfaces/IdentityIdentifiersInterface.ts
Ajout des extensions nécessaires au fonctionnement du projet dans la listes des extensions recommandées.
> [Vscode] extensions recommandées

- api/proxy/src/HttpTransport.ts
fix rate limiter for policy simulation
> fix rate limiter for policy simulation

- shell.nix
- tools/README.md
- tools/phone.js
- tools/phone.sh
Outil pour générer les fichiers de correspondance entre des uuids et des numéros de téléphone
> feat: generate phone file tool

- api/services/apdf/src/providers/APDFRepositoryProvider.ts
Utilisation du dernier millesime connu pour la récupération des données géo dans la les trajets APDF.
> [hotfix] Millesime APDF

- README.md
- api/package.json
Peut-être même qu'il faudrait skip de la migration geo et la lancer à part manuellement...
Elle timeout systématiquement je crois actuellement
> feat(yarn): env toggle for geo and sql migrations

- tools/README.md
- tools/phone.sh
Optim du script pour pointer vers les clés et ne pas compresser les fichiers.
Les tx de transfert sont suffisamment rapides sur les 4 clés en //.
> Phone tools

- api/services/policy/src/engine/policies/Cotentin.html.ts
- api/services/policy/src/engine/policies/Cotentin.spec.ts
- api/services/policy/src/engine/policies/Cotentin.ts
- api/services/policy/src/engine/policies/index.ts
```sql
INSERT INTO policy.policies (
territory_id,
start_date,
end_date,
name,
description,
unit,
status,
handler,
incentive_sum,
max_amount
) VALUES (
36295,
'2023-01-01T00:00:00+0100',
'2024-01-01T00:00:00+0100',
'#Cotentin_2023_01',
NULL,
'euro',
'active',
'cotentin_2023',
0,
15000000
);
```
> feat(policy): add cotentin

- api/services/user/src/notifications/SimulatePolicyNotification.ts
- shared/policy/common/classes/PolicyTemplateDescription.ts
https://github.com/betagouv/preuve-covoiturage/issues/2017
> fix(simulate): process PO review

- tools/phone.js
Ajout de `\n` à la fin de chaque _chunksize_
> Phone tool fix new line

- .github/workflows/deploy-nginx.yml
- dashboard/src/environments/environment.demo.ts
- docker-compose.dev.yml
- docker/nginx/Dockerfile
- docker/nginx/conf.d/default.conf
- docker/nginx/nginx.conf
- docker/nginx/scripts/buildconf.sh
- docker/nginx/scripts/domain.env
- docker/nginx/scripts/site.conf.tpl
- docker/nginx/shared/general.conf
- docker/nginx/shared/proxy.conf
- docker/nginx/shared/security.conf
- add a basic proxy nginx docker image
> Feat: nginx

- api/services/apdf/src/providers/APDFRepositoryProvider.ts
- api/services/policy/src/engine/policies/LaRochelle.ts
- api/services/policy/src/engine/policies/Pdll2023.spec.ts
- api/services/policy/src/engine/policies/Pdll2023.ts
- api/services/policy/src/engine/policies/Pmgf.html.ts
- api/services/policy/src/engine/policies/Vitre.ts
Fix de la requêtes de stats des APDF pour les tranches.
Fix des tranches de campagnes.
> Fix campagnes et APDF

- api/services/policy/src/engine/policies/Idfm.spec.ts
Ajout de tests explicites pour le calcul de jour de grève / pollution IDFM.
> Tests jours de grève IDFM

- api/services/cee/src/providers/CeeRepositoryProvider.ts
Utilise la distance calculée si la distance n'est pas fournie
> fix: use calc distance if distance not provided

- api/services/policy/src/actions/ListAction.ts
- api/services/policy/src/engine/policies/Pdll2023.ts
Les opérateurs n'étaient pas déclarés.
> [hotfix] ajout des opérateurs PDLL2023

- api/doc/cee.yaml
- api/proxy/src/HttpTransport.ts
- api/proxy/src/middlewares/rateLimiter.ts
> feat: explicit rate limiter configuration + split by cee

- api/doc/cee.yaml
> doc: improve 409 description

- api/services/policy/src/engine/policies/Idfm.ts
Jour de grève à valider avec IDFM avant de _merge_
> [IDFM] Jour de grève du 6 avril 2023

- api/services/acquisition/src/actions/ProcessJourneyAction.spec.ts
- api/services/acquisition/src/actions/ProcessJourneyAction.ts
> fix: acquisition stack is stuck

- api/services/policy/src/actions/FinalizeAction.ts
> Patch finalize days

- api/db/migrations/20230316000000-create_incentive_table.js
- api/db/migrations/carpool/20230316000000_create_incentive_table.down.sql
- api/db/migrations/carpool/20230316000000_create_incentive_table.up.sql
- api/providers/normalization/src/providers/NormalizationProvider.ts
- api/services/carpool/src/interfaces/Carpool.ts
- api/services/carpool/src/providers/CarpoolRepositoryProvider.integration.spec.ts
- api/services/carpool/src/providers/CarpoolRepositoryProvider.ts
- shared/carpool/crosscheck.contract.ts
> Feat: update incentive schema

- api/db/migrations/20230522000000-update_cee_identity_key copy.js
- api/db/migrations/cee/20230522000000-update_identity_key.down.sql
- api/db/migrations/cee/20230522000000-update_identity_key.up.sql
- api/services/cee/package.json
- api/services/cee/src/actions/RegisterCeeAction.ts
- api/services/cee/src/actions/SimulateCeeAction.ts
- api/services/cee/src/helpers/crypt.ts
- api/services/cee/src/interfaces/CeeRepositoryProviderInterface.ts
- api/services/cee/src/providers/CeeRepositoryProvider.integration.spec.ts
- api/services/cee/src/providers/CeeRepositoryProvider.ts
- api/yarn.lock
- réinitialisation de `identity_key`
- suppression du hash avant stockage
- fix sur les erreurs 500
> cee: fix identity key

- api/services/trip/package.json
- api/services/trip/src/actions/file/BuildFile.ts
- api/yarn.lock
Fix du décalage des colonnes dans l'export en forçant l'utilisation de guillemets sur tous les champs, même vides.
#2111
> Décalage de colonnes sur l'export

- .github/workflows/analysis-dep.yml
- .github/workflows/analysis-linter.yml
- .github/workflows/analysis-test-e2e.yml
- .github/workflows/analysis-test-integration.yml
- .github/workflows/analysis-test-unit.yml
- .github/workflows/deploy-dashboard-production.yml
- .github/workflows/deploy-doc-production.yml
- api/ilos/common/package.json
- api/package.json
- api/yarn.lock
- dashboard/package.json
- doc/package.json
- docker/api/Dockerfile
- docker/api/prod/Dockerfile
- docker/arena/Dockerfile
- docker/dashboard/Dockerfile
- docker/dashboard/prod/Dockerfile
- docker/lint/Dockerfile
- shell.nix
> chore: upgrade to node 20

- api/doc/v3.yaml
- doc/docs/operateurs/api-v3.md
> doc: ajout des délai dans la doc technique

- notebooks/scripts/production/interoperators-fraud-manual.ipynb
- notebooks/scripts/production/interoperators-fraud.ipynb
Ajout d'un script pour la fraude inter avec start_date et end_date
> feat(notebook): add manual notebook execution

- api/db/migrations/20230703000000-add_id_key_on_cee_error.js
- api/db/migrations/cee/20230703000000-update_identity_key_error.down.sql
- api/db/migrations/cee/20230703000000-update_identity_key_error.up.sql
- api/doc/cee.yaml
- api/services/cee/src/actions/RegisterCeeAction.ts
- api/services/cee/src/actions/SimulateCeeAction.ts
- api/services/cee/src/interfaces/CeeRepositoryProviderInterface.ts
- api/services/cee/src/providers/CeeRepositoryProvider.integration.spec.ts
- api/services/cee/src/providers/CeeRepositoryProvider.ts
- shared/cee/common/CeeApplicationInterface.ts
- shared/cee/simulateApplication.schema.ts
- add identity_key on simulate endpoint #2171 
- add journey_id and status in case of 409 #2164
> Feat: cee identity_key on simulate

- .github/workflows/deploy-dashboard-production.yml
- api/doc/v3.yaml
- api/services/policy/src/engine/policies/Idfm.html.ts
- api/services/policy/src/engine/policies/Idfm.ts
- api/services/policy/src/engine/policies/PaysBasque.ts
Fix https://github.com/betagouv/preuve-covoiturage/actions/runs/5462731349/jobs/9942484941
> fix(github): add legacy provider for build

- api/services/cee/src/actions/ImportCeeIdentityAction.ts
- api/services/cee/src/providers/CeeRepositoryProvider.ts
- avoid import errors if datetime is provided without the right TS
- accept update with uuid on a specific cee applicaiton
> Fix: cee id import

- api/services/cee/src/actions/RegisterCeeAction.ts
> fix: avoid erasing identity_key

- notebooks/scripts/production/users-patterns-insights-manual.ipynb
- notebooks/scripts/production/users-patterns-insights.ipynb
fix: replace group by groupe keyword
> fix: replace group by groupe keyword

- .vscode/launch.json
- api/doc/v3.yaml
- api/services/acquisition/src/actions/StatusJourneyAction.ts
- api/services/acquisition/src/interfaces/AcquisitionRepositoryProviderInterface.ts
- api/services/acquisition/src/providers/AcquisitionRepositoryProvider.integration.spec.ts
- api/services/acquisition/src/providers/AcquisitionRepositoryProvider.ts
- doc/docs/contribuer/api/providers/file/index.md
- doc/docs/contribuer/api/providers/storage/index.md
- shared/acquisition/status.contract.ts
> feat(acquisition): remove unused message field

- notebooks/scripts/production/computes/carpool_overlaps.py
- notebooks/scripts/production/interoperators-fraud-manual.ipynb
- notebooks/scripts/production/interoperators-fraud.ipynb
- notebooks/scripts/tests/test_compute_overlap_columns.py
Exclusion de l'opérateur covoiturage entreprise pour le moment
> Add optional column for overlaps and add tests

- api/db/migrations/20230915000000-update_observatory_procedures.js
- api/db/migrations/observatory/007_update_insert_monthly_flux_procedure.up.sql
- api/db/migrations/observatory/008_update_insert_monthly_occupation_procedure.up.sql
- api/db/migrations/observatory/009_update_insert_monthly_distribution_procedure.up.sql
- public/next.config.js
- public/src/components/layout/Navigation.tsx
fix sur le menu de navigation du site et sur les fonctions d'importation de données de l'observatoire
> fix(public): recette site

- api/services/trip/src/ServiceProvider.ts
- api/services/trip/src/actions/BuildExportAction.ts
- api/services/trip/src/commands/PublishOpendataCommand.ts
Suppression du CRON redis dans l'action et création d'une commande pour utilisation dans les CRON de l'infra.
> feat(opendata): publish command

- api/ilos/connection-postgres/package.json
- api/ilos/connection-postgres/src/PostgresConnection.integration.spec.ts
- api/ilos/connection-postgres/src/PostgresConnection.ts
- api/ilos/transport-redis/src/QueueTransport.ts
- api/package-lock.json
- api/proxy/src/config/proxy.ts
- api/services/apdf/src/providers/APDFRepositoryProvider.ts
- api/services/policy/src/providers/IncentiveRepositoryProvider.ts
- api/services/policy/src/providers/TripRepositoryProvider.ts
- api/services/trip/src/actions/BuildExportAction.ts
- api/services/trip/src/actions/SendExportAction.ts
- api/services/trip/src/actions/file/BuildFile.ts
- api/services/trip/src/providers/TripRepositoryProvider.ts
- docker-compose.yml
- docker/redis/Dockerfile
- tests/cypress/integration/unit/emailHelpers.spec.ts
Promisify de `pg-cursor` `read` function.
Bump versions
> fix(export): Promisify cursor.read

- api/db/migrations/20230920143743795-add-employer.js
- api/db/migrations/honor/20230920143743795-add-employer.down.sql
- api/db/migrations/honor/20230920143743795-add-employer.up.sql
- api/proxy/src/HttpTransport.ts
- api/services/honor/src/actions/SaveAction.ts
- api/services/honor/src/providers/HonorRepositoryProvider.ts
- attestation/src/app/pages/form-limited/form-limited.component.ts
- attestation/src/app/pages/form-public/form-public.component.ts
- attestation/src/app/services/counter.service.ts
- shared/honor/save.contract.ts
- shared/honor/save.schema.ts
Ajout du champ "employeur" dans les données capturées par le compteur d'attestations.
> feat(honor): track employer name

- api/ilos/framework/src/cli.ts
suppression de la bannière Ilos dans la console
> fix(cli): rm banner

- .github/workflows/analysis.yml
- integration.sh
Fix sur les tests d'intégration
> add delay for services to start in integration tests

- api/services/certificate/src/providers/CarpoolPgRepositoryProvider.ts
Fix de la méthode de calcul des paiements des attestations
> fix(certificates): use APIv3 data to calculate certificates

- api/src/pdc/services/apdf/providers/excel/SlicesWorksheetWriter.ts
fix  https://covoiturage-betagouv.zammad.com/#ticket/zoom/2922
> fix start slice formula

- api/src/pdc/services/user/notifications/ExportCSVNotification.ts
Changement du type de fichier d'export dans l'email envoyé à l'utilisateur.
> fix: export email wording

- api/deno.json
- api/src/pdc/services/policy/engine/policies/20240902_PetrLunevillois.ts
- api/src/pdc/services/policy/engine/policies/20240902_PetrLunevillois.unit.spec.ts
fix de la campagne PETR Lunevillois 2024/2025.
Inclusion des trajets dont le départ OU l'arrivée sont dans l'AOM.
> fix: PETR campaign

- .github/pull_request_template.md
- api/specs/api-v3.1.yaml
Mise en forme des infos du fichier OpenAPI v3.1 pour bump.sh
Je squash la PR et vérifie que le message de commit utilise
[la convention d'Angular](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format) :
```
│       │
│
```
- feat: A new feature (Minor bump)
- …
> update v3.1 openapi file

- api/src/pdc/services/policy/engine/policies/20210520_IDFM.html.ts
- api/src/pdc/services/policy/engine/policies/20210520_IDFM.ts
- api/src/pdc/services/policy/engine/policies/20240101_SMTC2024Passenger.html.ts
- api/src/pdc/services/policy/engine/policies/20240101_SMTCDriver.html.ts
Prolongement des campagnes SMTC au 31/12/2025
https://covoiturage-betagouv.zammad.com/#ticket/zoom/4677
Ajout de jour de grève SNCF le 11/12/2024 sur IDFM
https://covoiturage-betagouv.zammad.com/#ticket/zoom/4675
```
│       │
│
```
- ci: …
> MAJ Campagnes

- api/specs/api-v3.2.yaml
<details>
```
│       │
│
```
- feat: A new …
> fix(doc): trigger deploy

- public/src/helpers/lists.ts
- public/src/hooks/useDashboard.ts
<details>
```
│       │
│
```
- feat: A new …
> fix: select date for 2025

- public/src/hooks/useDashboard.ts
<details>
```
│       │
│
```
- feat: A new …
> fix: obs dashboard trimester and semester date

- notebooks/analytics/fraudcheck/too_many_trips_flagued.ipynb
<details>
```
│       │
│
```
- feat: A new …
> feat(data): add notebook to check on tooo_many_trips flagued carpools

- api/specs/api-v3.0.yaml
- api/specs/api-v3.2.yaml
<details>
```
│       │
│
```
- feat: A new …
> doc(api): update 3.0 to deprecated, add anchor for trip status details

- api/src/pdc/services/policy/engine/policies/20250101_GrandChatellerault.html.ts
- api/src/pdc/services/policy/engine/policies/20250101_GrandChatellerault.ts
<details>
```
│       │
│
```
- feat: A new …
> fix(policy): update description for Grand Chatellerault

- api/src/pdc/services/policy/engine/policies/20240101_PaysDeLaLoire.html.ts
- api/src/pdc/services/policy/engine/policies/20240201_GrandChatellerault.html.ts
Mise à jour de la description PDLL et Chatellerault
> fix: update PDLL description

- public/src/hooks/useDashboard.ts
<details>
```
│       │
│
```
- feat: A new …
> fix: trimester select bug

- api/src/lib/crypto/index.ts
<details>
```
│       │
│
```
- feat: A new …
> fix(worker): add back worker crypto workaround

- api/specs/api-v3.3.yaml
<details>
```
│       │
│
```
- feat: A new …
> doc: fix fraud label detail and version mismatch

- app-front/src/providers/AuthProvider.tsx
<details>
```
│       │
│
```
- feat: A new …
> fix: add comment

- api/src/pdc/services/policy/engine/policies/20250101_PMGFxATMB.html.ts
- api/src/pdc/services/policy/engine/policies/20250101_PMGFxATMB.ts
- api/src/pdc/services/policy/engine/policies/20250101_PMGFxATMB.unit.spec.ts
https://covoiturage-betagouv.zammad.com/#ticket/zoom/5752
<details>
```
│       │
│
```
- …
> MAJ campagne PMGFxATMB

- .github/workflows/deploy-frontends-dashboardv2.yml
<details>
```
│       │
│
```
- feat: A new …
> fix: dashboard bucket var

- .github/workflows/deploy-frontends-many.yml
<details>
```
│       │
│
```
- feat: A new …
> fix: remove deploy dahshboard in deploy_frontend_many workflow

- .github/workflows/deploy-frontends-dashboardv2.yml
- .github/workflows/deploy-frontends-many.yml
<details>
```
│       │
│
```
- feat: A new …
> fix: workfows

- .github/workflows/deploy-frontends-dashboardv2.yml
<details>
```
│       │
│
```
- feat: A new …
> fix: var api

- api/src/ilos/connection-postgres/DenoPostgresConnection.ts
<details>
```
│       │
│
```
- feat: A new …
> fix(api): url decode password for encoded

- app-front/src/components/layout/AppHeader.tsx
<details>
```
│       │
│
```
- feat: A new …
> fix: ministry name

- api/e2e/scenarios/1-journeys/001-happy-path.test.ts
<details>
```
│       │
│
```
- feat: A new …
> test: should not have session header in api call

- app-front/src/app/activite/tabs/TabExport.tsx
- app-front/src/components/common/SelectPolicyPerimeter.tsx
- app-front/src/interfaces/dataInterface.ts
<details>
```
│       │
│
```
- feat: A new …
> fix(exports): use policy select for custom perimeters

- api/src/ilos/cli/commander.ts
- api/src/pdc/providers/carpool/providers/CarpoolStatusService.ts
- api/src/pdc/proxy/config/API_VERSION.ts
- api/src/pdc/services/acquisition/AcquisitionServiceProvider.ts
- api/src/pdc/services/acquisition/actions/StatusJourneyAction.ts
- api/src/pdc/services/acquisition/commands/JourneyStatusCommand.ts
```
just api journey:status <operator_id> <operator_journey_id...>
```
> Ajout de la commande journey:status
